package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 07 10:10:23 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FormationPayModaliteROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FormationPayModaliteROVOImpl() {
    }
}

