package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 01 11:34:03 UTC 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AccesEcListImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AccesEcListImpl() {
    }
}

