package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 11 11:21:42 GMT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InscriptionPedSemUeROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InscriptionPedSemUeROVOImpl() {
    }
}

