package model.readOnlyView;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 18 15:38:45 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompteEtabDecaisseRechROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdRepartition {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdStructure {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibRep {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdCompte {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdFormation {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdHistoriquesStructure {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdTypeCompte {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NumeroCompte {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Pourcentage {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdFormFrep {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdAnneesUnivers {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdSoldeCompte {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SoldeActuel {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SoldeInitial {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibTypeCmpte {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibStrc {
            protected Object get(CompteEtabDecaisseRechROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(CompteEtabDecaisseRechROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(CompteEtabDecaisseRechROVORowImpl object);

        protected abstract void put(CompteEtabDecaisseRechROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDREPARTITION = AttributesEnum.IdRepartition.index();
    public static final int IDSTRUCTURE = AttributesEnum.IdStructure.index();
    public static final int LIBREP = AttributesEnum.LibRep.index();
    public static final int IDCOMPTE = AttributesEnum.IdCompte.index();
    public static final int IDFORMATION = AttributesEnum.IdFormation.index();
    public static final int IDHISTORIQUESSTRUCTURE = AttributesEnum.IdHistoriquesStructure.index();
    public static final int IDTYPECOMPTE = AttributesEnum.IdTypeCompte.index();
    public static final int NUMEROCOMPTE = AttributesEnum.NumeroCompte.index();
    public static final int POURCENTAGE = AttributesEnum.Pourcentage.index();
    public static final int IDFORMFREP = AttributesEnum.IdFormFrep.index();
    public static final int IDANNEESUNIVERS = AttributesEnum.IdAnneesUnivers.index();
    public static final int IDSOLDECOMPTE = AttributesEnum.IdSoldeCompte.index();
    public static final int SOLDEACTUEL = AttributesEnum.SoldeActuel.index();
    public static final int SOLDEINITIAL = AttributesEnum.SoldeInitial.index();
    public static final int LIBTYPECMPTE = AttributesEnum.LibTypeCmpte.index();
    public static final int LIBSTRC = AttributesEnum.LibStrc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CompteEtabDecaisseRechROVORowImpl() {
    }
}

