package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 07 10:10:07 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FormationPayModaliteROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdFormationModalite {
            protected Object get(FormationPayModaliteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayModaliteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdModalite {
            protected Object get(FormationPayModaliteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayModaliteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdMoisDebut {
            protected Object get(FormationPayModaliteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayModaliteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AnneeDebut {
            protected Object get(FormationPayModaliteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayModaliteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdMoisFin {
            protected Object get(FormationPayModaliteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayModaliteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Duree {
            protected Object get(FormationPayModaliteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayModaliteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AnneeFin {
            protected Object get(FormationPayModaliteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayModaliteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(FormationPayModaliteROVORowImpl object);

        protected abstract void put(FormationPayModaliteROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDFORMATIONMODALITE = AttributesEnum.IdFormationModalite.index();
    public static final int IDMODALITE = AttributesEnum.IdModalite.index();
    public static final int IDMOISDEBUT = AttributesEnum.IdMoisDebut.index();
    public static final int ANNEEDEBUT = AttributesEnum.AnneeDebut.index();
    public static final int IDMOISFIN = AttributesEnum.IdMoisFin.index();
    public static final int DUREE = AttributesEnum.Duree.index();
    public static final int ANNEEFIN = AttributesEnum.AnneeFin.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FormationPayModaliteROVORowImpl() {
    }
}

