package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 27 12:12:29 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AnneeUniversSupROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AnneeUniversSupROVOImpl() {
    }
}

