package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Mar 13 18:00:27 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AutoInscPreinsROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Valide {
            protected Object get(AutoInscPreinsROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AutoInscPreinsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Numero {
            protected Object get(AutoInscPreinsROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AutoInscPreinsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdEtudiant {
            protected Object get(AutoInscPreinsROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AutoInscPreinsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdPersonne {
            protected Object get(AutoInscPreinsROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AutoInscPreinsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(AutoInscPreinsROVORowImpl object);

        protected abstract void put(AutoInscPreinsROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int VALIDE = AttributesEnum.Valide.index();
    public static final int NUMERO = AttributesEnum.Numero.index();
    public static final int IDETUDIANT = AttributesEnum.IdEtudiant.index();
    public static final int IDPERSONNE = AttributesEnum.IdPersonne.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AutoInscPreinsROVORowImpl() {
    }
}

