package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 01 11:59:03 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BeneficiaireROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdBeneficaire {
            protected Object get(BeneficiaireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(BeneficiaireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdStructure {
            protected Object get(BeneficiaireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(BeneficiaireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Nom {
            protected Object get(BeneficiaireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(BeneficiaireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NumCompteBanque {
            protected Object get(BeneficiaireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(BeneficiaireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NumeroCompte {
            protected Object get(BeneficiaireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(BeneficiaireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenom {
            protected Object get(BeneficiaireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(BeneficiaireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Proprietaire {
            protected Object get(BeneficiaireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(BeneficiaireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Telephone {
            protected Object get(BeneficiaireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(BeneficiaireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(BeneficiaireROVORowImpl object);

        protected abstract void put(BeneficiaireROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDBENEFICAIRE = AttributesEnum.IdBeneficaire.index();
    public static final int IDSTRUCTURE = AttributesEnum.IdStructure.index();
    public static final int NOM = AttributesEnum.Nom.index();
    public static final int NUMCOMPTEBANQUE = AttributesEnum.NumCompteBanque.index();
    public static final int NUMEROCOMPTE = AttributesEnum.NumeroCompte.index();
    public static final int PRENOM = AttributesEnum.Prenom.index();
    public static final int PROPRIETAIRE = AttributesEnum.Proprietaire.index();
    public static final int TELEPHONE = AttributesEnum.Telephone.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BeneficiaireROVORowImpl() {
    }
}

