package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 12 10:52:15 GMT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BoursierLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BoursierLOVImpl() {
    }
}

