package model.readOnlyView;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 18 16:53:18 GMT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DelibSemDataDetailNoteROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdNoteModeEnsInter {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdModeControleEc {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Libtcmc {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdCalendrierDeliberation {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Note {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdTypeControle {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdTypeVerrou {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibTcntl {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdFiliereUeSemstreEc {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Coefficient {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibEc {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdFiliereUeSemstre {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Codification {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibUe {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionPedSemUe {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdSemestre {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionPedSemestre {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IsDelibarable {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetAnnee {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdEtudiant {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Numero {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Nom {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenoms {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LieuNaissance {
            protected Object get(DelibSemDataDetailNoteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemDataDetailNoteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(DelibSemDataDetailNoteROVORowImpl object);

        protected abstract void put(DelibSemDataDetailNoteROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDNOTEMODEENSINTER = AttributesEnum.IdNoteModeEnsInter.index();
    public static final int IDMODECONTROLEEC = AttributesEnum.IdModeControleEc.index();
    public static final int LIBTCMC = AttributesEnum.Libtcmc.index();
    public static final int IDCALENDRIERDELIBERATION = AttributesEnum.IdCalendrierDeliberation.index();
    public static final int NOTE = AttributesEnum.Note.index();
    public static final int IDTYPECONTROLE = AttributesEnum.IdTypeControle.index();
    public static final int IDTYPEVERROU = AttributesEnum.IdTypeVerrou.index();
    public static final int LIBTCNTL = AttributesEnum.LibTcntl.index();
    public static final int IDFILIEREUESEMSTREEC = AttributesEnum.IdFiliereUeSemstreEc.index();
    public static final int COEFFICIENT = AttributesEnum.Coefficient.index();
    public static final int LIBEC = AttributesEnum.LibEc.index();
    public static final int IDFILIEREUESEMSTRE = AttributesEnum.IdFiliereUeSemstre.index();
    public static final int CODIFICATION = AttributesEnum.Codification.index();
    public static final int LIBUE = AttributesEnum.LibUe.index();
    public static final int IDINSCRIPTIONPEDSEMUE = AttributesEnum.IdInscriptionPedSemUe.index();
    public static final int IDSEMESTRE = AttributesEnum.IdSemestre.index();
    public static final int IDINSCRIPTIONPEDSEMESTRE = AttributesEnum.IdInscriptionPedSemestre.index();
    public static final int ISDELIBARABLE = AttributesEnum.IsDelibarable.index();
    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int IDETUDIANT = AttributesEnum.IdEtudiant.index();
    public static final int NUMERO = AttributesEnum.Numero.index();
    public static final int NOM = AttributesEnum.Nom.index();
    public static final int PRENOMS = AttributesEnum.Prenoms.index();
    public static final int LIEUNAISSANCE = AttributesEnum.LieuNaissance.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DelibSemDataDetailNoteROVORowImpl() {
    }
}

