package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 22 17:35:54 CET 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DelibUeFilEcTypeCntrlROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdFiliereUeSemstreEc {
            protected Object get(DelibUeFilEcTypeCntrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibUeFilEcTypeCntrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetAnnee {
            protected Object get(DelibUeFilEcTypeCntrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibUeFilEcTypeCntrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdTypeControle {
            protected Object get(DelibUeFilEcTypeCntrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibUeFilEcTypeCntrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Typecntrl {
            protected Object get(DelibUeFilEcTypeCntrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibUeFilEcTypeCntrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Modecntrl {
            protected Object get(DelibUeFilEcTypeCntrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibUeFilEcTypeCntrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(DelibUeFilEcTypeCntrlROVORowImpl object);

        protected abstract void put(DelibUeFilEcTypeCntrlROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDFILIEREUESEMSTREEC = AttributesEnum.IdFiliereUeSemstreEc.index();
    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int IDTYPECONTROLE = AttributesEnum.IdTypeControle.index();
    public static final int TYPECNTRL = AttributesEnum.Typecntrl.index();
    public static final int MODECNTRL = AttributesEnum.Modecntrl.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DelibUeFilEcTypeCntrlROVORowImpl() {
    }
}

