package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 15 16:17:32 GMT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DelibSemRepCritereCompLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DelibSemRepCritereCompLOVImpl() {
    }
}

