package model.readOnlyView;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 23 09:51:42 GMT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DelibDataROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdFiliereUeSemstre {
            protected Object get(DelibDataROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibDataROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Codification {
            protected Object get(DelibDataROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibDataROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(DelibDataROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibDataROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetAnnee {
            protected Object get(DelibDataROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibDataROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdFiliereUeSemstreEc {
            protected Object get(DelibDataROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibDataROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Coefficient {
            protected Object get(DelibDataROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibDataROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibEc {
            protected Object get(DelibDataROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibDataROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Codification1 {
            protected Object get(DelibDataROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibDataROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(DelibDataROVORowImpl object);

        protected abstract void put(DelibDataROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDFILIEREUESEMSTRE = AttributesEnum.IdFiliereUeSemstre.index();
    public static final int CODIFICATION = AttributesEnum.Codification.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int IDFILIEREUESEMSTREEC = AttributesEnum.IdFiliereUeSemstreEc.index();
    public static final int COEFFICIENT = AttributesEnum.Coefficient.index();
    public static final int LIBEC = AttributesEnum.LibEc.index();
    public static final int CODIFICATION1 = AttributesEnum.Codification1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DelibDataROVORowImpl() {
    }
}

