package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 01 04:50:08 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailsCompteROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DetailsCompteROVOImpl() {
    }
}

