package model.readOnlyView;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 09 12:04:23 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DiplomeEtudiantGradeROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdDiplomeEtudiant {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateObtention {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Numero {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Nom {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenoms {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateNaissance {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdEtab {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdGradesFormation {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdOption {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdSpecialite {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdTypeMention {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Lieu {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaysObtention {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Serie {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LieuNaissance {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Adresse {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PieceIdentification {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EtablissementExterneVO1 {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GradesFormationVO1 {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OptionsVO1 {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SpecialitesVO1 {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TypeMentionVO1 {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaysVO1 {
            protected Object get(DiplomeEtudiantGradeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DiplomeEtudiantGradeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected abstract Object get(DiplomeEtudiantGradeROVORowImpl object);

        protected abstract void put(DiplomeEtudiantGradeROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDDIPLOMEETUDIANT = AttributesEnum.IdDiplomeEtudiant.index();
    public static final int DATEOBTENTION = AttributesEnum.DateObtention.index();
    public static final int NUMERO = AttributesEnum.Numero.index();
    public static final int NOM = AttributesEnum.Nom.index();
    public static final int PRENOMS = AttributesEnum.Prenoms.index();
    public static final int DATENAISSANCE = AttributesEnum.DateNaissance.index();
    public static final int IDETAB = AttributesEnum.IdEtab.index();
    public static final int IDGRADESFORMATION = AttributesEnum.IdGradesFormation.index();
    public static final int IDOPTION = AttributesEnum.IdOption.index();
    public static final int IDSPECIALITE = AttributesEnum.IdSpecialite.index();
    public static final int IDTYPEMENTION = AttributesEnum.IdTypeMention.index();
    public static final int LIEU = AttributesEnum.Lieu.index();
    public static final int PAYSOBTENTION = AttributesEnum.PaysObtention.index();
    public static final int SERIE = AttributesEnum.Serie.index();
    public static final int LIEUNAISSANCE = AttributesEnum.LieuNaissance.index();
    public static final int ADRESSE = AttributesEnum.Adresse.index();
    public static final int PIECEIDENTIFICATION = AttributesEnum.PieceIdentification.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int ETABLISSEMENTEXTERNEVO1 = AttributesEnum.EtablissementExterneVO1.index();
    public static final int GRADESFORMATIONVO1 = AttributesEnum.GradesFormationVO1.index();
    public static final int OPTIONSVO1 = AttributesEnum.OptionsVO1.index();
    public static final int SPECIALITESVO1 = AttributesEnum.SpecialitesVO1.index();
    public static final int TYPEMENTIONVO1 = AttributesEnum.TypeMentionVO1.index();
    public static final int PAYSVO1 = AttributesEnum.PaysVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DiplomeEtudiantGradeROVORowImpl() {
    }
}

