package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 02 11:29:43 GMT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DoubleAssimileTireeLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DoubleAssimileTireeLOVImpl() {
    }
}

