package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 02 14:54:50 CET 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EcEvalTypeCntrlNewROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EcEvalTypeCntrlNewROVOImpl() {
    }
}

