package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 22 09:37:41 CET 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EcEvalExportEtdROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdFiliereUeSemstreEc {
            protected Object get(EcEvalExportEtdROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalExportEtdROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdFiliereUeSemstre {
            protected Object get(EcEvalExportEtdROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalExportEtdROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdCalendrierDeliberation {
            protected Object get(EcEvalExportEtdROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalExportEtdROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(EcEvalExportEtdROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalExportEtdROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Codification {
            protected Object get(EcEvalExportEtdROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalExportEtdROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetAnnee {
            protected Object get(EcEvalExportEtdROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalExportEtdROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AncienCode {
            protected Object get(EcEvalExportEtdROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalExportEtdROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EtudiantExportListROVO {
            protected Object get(EcEvalExportEtdROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalExportEtdROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(EcEvalExportEtdROVORowImpl object);

        protected abstract void put(EcEvalExportEtdROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDFILIEREUESEMSTREEC = AttributesEnum.IdFiliereUeSemstreEc.index();
    public static final int IDFILIEREUESEMSTRE = AttributesEnum.IdFiliereUeSemstre.index();
    public static final int IDCALENDRIERDELIBERATION = AttributesEnum.IdCalendrierDeliberation.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int CODIFICATION = AttributesEnum.Codification.index();
    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int ANCIENCODE = AttributesEnum.AncienCode.index();
    public static final int ETUDIANTEXPORTLISTROVO = AttributesEnum.EtudiantExportListROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EcEvalExportEtdROVORowImpl() {
    }
}

