package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 25 22:58:06 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EcEvalTypeCtrlModeCtrlROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdModeControle {
            protected Object get(EcEvalTypeCtrlModeCtrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalTypeCtrlModeCtrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibModeCtrl {
            protected Object get(EcEvalTypeCtrlModeCtrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalTypeCtrlModeCtrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdFiliereUeSemstreEc {
            protected Object get(EcEvalTypeCtrlModeCtrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalTypeCtrlModeCtrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdModeControleEc {
            protected Object get(EcEvalTypeCtrlModeCtrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalTypeCtrlModeCtrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdTypeControle {
            protected Object get(EcEvalTypeCtrlModeCtrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalTypeCtrlModeCtrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetteAnnee {
            protected Object get(EcEvalTypeCtrlModeCtrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EcEvalTypeCtrlModeCtrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(EcEvalTypeCtrlModeCtrlROVORowImpl object);

        protected abstract void put(EcEvalTypeCtrlModeCtrlROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDMODECONTROLE = AttributesEnum.IdModeControle.index();
    public static final int LIBMODECTRL = AttributesEnum.LibModeCtrl.index();
    public static final int IDFILIEREUESEMSTREEC = AttributesEnum.IdFiliereUeSemstreEc.index();
    public static final int IDMODECONTROLEEC = AttributesEnum.IdModeControleEc.index();
    public static final int IDTYPECONTROLE = AttributesEnum.IdTypeControle.index();
    public static final int IDPARCOURSMAQUETTEANNEE = AttributesEnum.IdParcoursMaquetteAnnee.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EcEvalTypeCtrlModeCtrlROVORowImpl() {
    }
}

