package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 12 10:35:40 UTC 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EtudiantSaisieMemoireROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdEtudiant {
            protected Object get(EtudiantSaisieMemoireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantSaisieMemoireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Numero {
            protected Object get(EtudiantSaisieMemoireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantSaisieMemoireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenoms {
            protected Object get(EtudiantSaisieMemoireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantSaisieMemoireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Nom {
            protected Object get(EtudiantSaisieMemoireROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantSaisieMemoireROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(EtudiantSaisieMemoireROVORowImpl object);

        protected abstract void put(EtudiantSaisieMemoireROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDETUDIANT = AttributesEnum.IdEtudiant.index();
    public static final int NUMERO = AttributesEnum.Numero.index();
    public static final int PRENOMS = AttributesEnum.Prenoms.index();
    public static final int NOM = AttributesEnum.Nom.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EtudiantSaisieMemoireROVORowImpl() {
    }
}

