package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 12 12:33:34 CET 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EtudiantsRenonciationNoteImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EtudiantsRenonciationNoteImpl() {
    }
}

