package model.readOnlyView;

import java.sql.Timestamp;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 02 10:47:39 UTC 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EtudiantsDiplomesROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdEtudiant {
            protected Object get(EtudiantsDiplomesROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantsDiplomesROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Numero {
            protected Object get(EtudiantsDiplomesROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantsDiplomesROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenoms {
            protected Object get(EtudiantsDiplomesROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantsDiplomesROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Nom {
            protected Object get(EtudiantsDiplomesROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantsDiplomesROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateNaissance {
            protected Object get(EtudiantsDiplomesROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantsDiplomesROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LieuNaissance {
            protected Object get(EtudiantsDiplomesROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantsDiplomesROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetAnnee {
            protected Object get(EtudiantsDiplomesROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantsDiplomesROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Datesoutenanceref {
            protected Object get(EtudiantsDiplomesROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantsDiplomesROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IsUpdatable {
            protected Object get(EtudiantsDiplomesROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantsDiplomesROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(EtudiantsDiplomesROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantsDiplomesROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        isToUpdate {
            protected Object get(EtudiantsDiplomesROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EtudiantsDiplomesROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(EtudiantsDiplomesROVORowImpl object);

        protected abstract void put(EtudiantsDiplomesROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDETUDIANT = AttributesEnum.IdEtudiant.index();
    public static final int NUMERO = AttributesEnum.Numero.index();
    public static final int PRENOMS = AttributesEnum.Prenoms.index();
    public static final int NOM = AttributesEnum.Nom.index();
    public static final int DATENAISSANCE = AttributesEnum.DateNaissance.index();
    public static final int LIEUNAISSANCE = AttributesEnum.LieuNaissance.index();
    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int DATESOUTENANCEREF = AttributesEnum.Datesoutenanceref.index();
    public static final int ISUPDATABLE = AttributesEnum.IsUpdatable.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int ISTOUPDATE = AttributesEnum.isToUpdate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EtudiantsDiplomesROVORowImpl() {
    }
}

