package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 10 10:09:53 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FonctionnalitesUsersROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdFonctionnalite {
            protected Object get(FonctionnalitesUsersROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FonctionnalitesUsersROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(FonctionnalitesUsersROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FonctionnalitesUsersROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UrlAction {
            protected Object get(FonctionnalitesUsersROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FonctionnalitesUsersROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CheminImage {
            protected Object get(FonctionnalitesUsersROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FonctionnalitesUsersROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Ordre {
            protected Object get(FonctionnalitesUsersROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FonctionnalitesUsersROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdModule {
            protected Object get(FonctionnalitesUsersROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FonctionnalitesUsersROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdUtilisateur {
            protected Object get(FonctionnalitesUsersROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FonctionnalitesUsersROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Active {
            protected Object get(FonctionnalitesUsersROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FonctionnalitesUsersROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(FonctionnalitesUsersROVORowImpl object);

        protected abstract void put(FonctionnalitesUsersROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDFONCTIONNALITE = AttributesEnum.IdFonctionnalite.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int URLACTION = AttributesEnum.UrlAction.index();
    public static final int CHEMINIMAGE = AttributesEnum.CheminImage.index();
    public static final int ORDRE = AttributesEnum.Ordre.index();
    public static final int IDMODULE = AttributesEnum.IdModule.index();
    public static final int IDUTILISATEUR = AttributesEnum.IdUtilisateur.index();
    public static final int ACTIVE = AttributesEnum.Active.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FonctionnalitesUsersROVORowImpl() {
    }
}

