package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 17 09:10:49 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FormPayCompteFormROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FormPayCompteFormROVOImpl() {
    }
}

