package model.readOnlyView;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 01 10:10:57 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FormationPayanteROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdFormation {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdCycle {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdGradesFormation {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdHistoriquesStructure {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdMention {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdOrganisationEtude {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdTypeFormation {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibForm {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibCourtForm {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Ouvert {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Payante {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Role {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdUtilisateur {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibDept {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibCourtDept {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdStructure {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibCourtEtab {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibEtab {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Niveau {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibCourtMention {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibMention {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibCourtGrade {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibGrade {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibCourtDomaine {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdAnneesUnivers {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNiveauFormationParcours {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibNivForm {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibDomaine {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NivFormPayanteROVO {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RepartitionROVO {
            protected Object get(FormationPayanteROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FormationPayanteROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(FormationPayanteROVORowImpl object);

        protected abstract void put(FormationPayanteROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDFORMATION = AttributesEnum.IdFormation.index();
    public static final int IDCYCLE = AttributesEnum.IdCycle.index();
    public static final int IDGRADESFORMATION = AttributesEnum.IdGradesFormation.index();
    public static final int IDHISTORIQUESSTRUCTURE = AttributesEnum.IdHistoriquesStructure.index();
    public static final int IDMENTION = AttributesEnum.IdMention.index();
    public static final int IDORGANISATIONETUDE = AttributesEnum.IdOrganisationEtude.index();
    public static final int IDTYPEFORMATION = AttributesEnum.IdTypeFormation.index();
    public static final int LIBFORM = AttributesEnum.LibForm.index();
    public static final int LIBCOURTFORM = AttributesEnum.LibCourtForm.index();
    public static final int OUVERT = AttributesEnum.Ouvert.index();
    public static final int PAYANTE = AttributesEnum.Payante.index();
    public static final int ROLE = AttributesEnum.Role.index();
    public static final int IDUTILISATEUR = AttributesEnum.IdUtilisateur.index();
    public static final int LIBDEPT = AttributesEnum.LibDept.index();
    public static final int LIBCOURTDEPT = AttributesEnum.LibCourtDept.index();
    public static final int IDSTRUCTURE = AttributesEnum.IdStructure.index();
    public static final int LIBCOURTETAB = AttributesEnum.LibCourtEtab.index();
    public static final int LIBETAB = AttributesEnum.LibEtab.index();
    public static final int NIVEAU = AttributesEnum.Niveau.index();
    public static final int LIBCOURTMENTION = AttributesEnum.LibCourtMention.index();
    public static final int LIBMENTION = AttributesEnum.LibMention.index();
    public static final int LIBCOURTGRADE = AttributesEnum.LibCourtGrade.index();
    public static final int LIBGRADE = AttributesEnum.LibGrade.index();
    public static final int LIBCOURTDOMAINE = AttributesEnum.LibCourtDomaine.index();
    public static final int IDANNEESUNIVERS = AttributesEnum.IdAnneesUnivers.index();
    public static final int IDNIVEAUFORMATIONPARCOURS = AttributesEnum.IdNiveauFormationParcours.index();
    public static final int LIBNIVFORM = AttributesEnum.LibNivForm.index();
    public static final int LIBDOMAINE = AttributesEnum.LibDomaine.index();
    public static final int NIVFORMPAYANTEROVO = AttributesEnum.NivFormPayanteROVO.index();
    public static final int REPARTITIONROVO = AttributesEnum.RepartitionROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FormationPayanteROVORowImpl() {
    }
}

