package model.readOnlyView;

import model.updatableview.NotesModeEnseignementInterVORowImpl;
import model.updatableview.NotesModeEnseignementVORowImpl;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 27 18:27:34 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GenAnonymatROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdGenAnonymat {
            protected Object get(GenAnonymatROVORowImpl obj) {
                return obj.getIdGenAnonymat();
            }

            protected void put(GenAnonymatROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdAnonymat {
            protected Object get(GenAnonymatROVORowImpl obj) {
                return obj.getIdAnonymat();
            }

            protected void put(GenAnonymatROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdEtudiant {
            protected Object get(GenAnonymatROVORowImpl obj) {
                return obj.getIdEtudiant();
            }

            protected void put(GenAnonymatROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Anonymat {
            protected Object get(GenAnonymatROVORowImpl obj) {
                return obj.getAnonymat();
            }

            protected void put(GenAnonymatROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NotesModeEnseignementVO {
            protected Object get(GenAnonymatROVORowImpl obj) {
                return obj.getNotesModeEnseignementVO();
            }

            protected void put(GenAnonymatROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NotesModeEnseignementInterVO {
            protected Object get(GenAnonymatROVORowImpl obj) {
                return obj.getNotesModeEnseignementInterVO();
            }

            protected void put(GenAnonymatROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(GenAnonymatROVORowImpl object);

        protected abstract void put(GenAnonymatROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDGENANONYMAT = AttributesEnum.IdGenAnonymat.index();
    public static final int IDANONYMAT = AttributesEnum.IdAnonymat.index();
    public static final int IDETUDIANT = AttributesEnum.IdEtudiant.index();
    public static final int ANONYMAT = AttributesEnum.Anonymat.index();
    public static final int NOTESMODEENSEIGNEMENTVO = AttributesEnum.NotesModeEnseignementVO.index();
    public static final int NOTESMODEENSEIGNEMENTINTERVO = AttributesEnum.NotesModeEnseignementInterVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GenAnonymatROVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute IdGenAnonymat.
     * @return the IdGenAnonymat
     */
    public Long getIdGenAnonymat() {
        return (Long) getAttributeInternal(IDGENANONYMAT);
    }

    /**
     * Gets the attribute value for the calculated attribute IdAnonymat.
     * @return the IdAnonymat
     */
    public Long getIdAnonymat() {
        return (Long) getAttributeInternal(IDANONYMAT);
    }

    /**
     * Gets the attribute value for the calculated attribute IdEtudiant.
     * @return the IdEtudiant
     */
    public Long getIdEtudiant() {
        return (Long) getAttributeInternal(IDETUDIANT);
    }

    /**
     * Gets the attribute value for the calculated attribute Anonymat.
     * @return the Anonymat
     */
    public String getAnonymat() {
        return (String) getAttributeInternal(ANONYMAT);
    }

    /**
     * Gets the associated <code>NotesModeEnseignementVORowImpl</code> using master-detail link NotesModeEnseignementVO.
     */
    public NotesModeEnseignementVORowImpl getNotesModeEnseignementVO() {
        return (NotesModeEnseignementVORowImpl) getAttributeInternal(NOTESMODEENSEIGNEMENTVO);
    }

    /**
     * Sets the master-detail link NotesModeEnseignementVO between this object and <code>value</code>.
     */
    public void setNotesModeEnseignementVO(NotesModeEnseignementVORowImpl value) {
        setAttributeInternal(NOTESMODEENSEIGNEMENTVO, value);
    }


    /**
     * Gets the associated <code>NotesModeEnseignementInterVORowImpl</code> using master-detail link NotesModeEnseignementInterVO.
     */
    public NotesModeEnseignementInterVORowImpl getNotesModeEnseignementInterVO() {
        return (NotesModeEnseignementInterVORowImpl) getAttributeInternal(NOTESMODEENSEIGNEMENTINTERVO);
    }

    /**
     * Sets the master-detail link NotesModeEnseignementInterVO between this object and <code>value</code>.
     */
    public void setNotesModeEnseignementInterVO(NotesModeEnseignementInterVORowImpl value) {
        setAttributeInternal(NOTESMODEENSEIGNEMENTINTERVO, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

