package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 02 13:23:05 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getsemestregradeROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public getsemestregradeROVOImpl() {
    }
}

