package model.readOnlyView;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 23 15:58:26 UTC 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class grhUserROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        NoAgent {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibClassification {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CodeMatricule {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenom {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Nom {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NomMarital {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Cin {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateRecrutement {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibGrade {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Emailucad {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibStructure {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Sexe {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Civilite {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateNaissance {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Nationalite {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LieuNaissance {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Telephone {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Adresse {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Email {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CodeStr {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AncienCode {
            protected Object get(grhUserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(grhUserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(grhUserROVORowImpl object);

        protected abstract void put(grhUserROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int NOAGENT = AttributesEnum.NoAgent.index();
    public static final int LIBCLASSIFICATION = AttributesEnum.LibClassification.index();
    public static final int CODEMATRICULE = AttributesEnum.CodeMatricule.index();
    public static final int PRENOM = AttributesEnum.Prenom.index();
    public static final int NOM = AttributesEnum.Nom.index();
    public static final int NOMMARITAL = AttributesEnum.NomMarital.index();
    public static final int CIN = AttributesEnum.Cin.index();
    public static final int DATERECRUTEMENT = AttributesEnum.DateRecrutement.index();
    public static final int LIBGRADE = AttributesEnum.LibGrade.index();
    public static final int EMAILUCAD = AttributesEnum.Emailucad.index();
    public static final int LIBSTRUCTURE = AttributesEnum.LibStructure.index();
    public static final int SEXE = AttributesEnum.Sexe.index();
    public static final int CIVILITE = AttributesEnum.Civilite.index();
    public static final int DATENAISSANCE = AttributesEnum.DateNaissance.index();
    public static final int NATIONALITE = AttributesEnum.Nationalite.index();
    public static final int LIEUNAISSANCE = AttributesEnum.LieuNaissance.index();
    public static final int TELEPHONE = AttributesEnum.Telephone.index();
    public static final int ADRESSE = AttributesEnum.Adresse.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int CODESTR = AttributesEnum.CodeStr.index();
    public static final int ANCIENCODE = AttributesEnum.AncienCode.index();

    /**
     * This is the default constructor (do not remove).
     */
    public grhUserROVORowImpl() {
    }
}

