package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 10 11:45:28 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HistoMobiliteROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HistoMobiliteROVOImpl() {
    }
}

