package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 11 09:16:45 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InscPedSemRedoubleROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdAnneesUnivers {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibAnnee {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdEtudiant {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionAdmin {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InscLigne {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EtatInscrEtatInscrId {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionPedagogique {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetAnnee {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CumulCredit {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DetteCredit {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionPedSemestre {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdSemestre {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InsPedValide {
            protected Object get(InscPedSemRedoubleROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedSemRedoubleROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(InscPedSemRedoubleROVORowImpl object);

        protected abstract void put(InscPedSemRedoubleROVORowImpl object, Object value);

        protected int index() {
            return InscPedSemRedoubleROVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return InscPedSemRedoubleROVORowImpl.AttributesEnum.firstIndex() + InscPedSemRedoubleROVORowImpl.AttributesEnum
                                                                                                            .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = InscPedSemRedoubleROVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDANNEESUNIVERS = AttributesEnum.IdAnneesUnivers.index();
    public static final int LIBANNEE = AttributesEnum.LibAnnee.index();
    public static final int IDETUDIANT = AttributesEnum.IdEtudiant.index();
    public static final int IDINSCRIPTIONADMIN = AttributesEnum.IdInscriptionAdmin.index();
    public static final int INSCLIGNE = AttributesEnum.InscLigne.index();
    public static final int ETATINSCRETATINSCRID = AttributesEnum.EtatInscrEtatInscrId.index();
    public static final int IDINSCRIPTIONPEDAGOGIQUE = AttributesEnum.IdInscriptionPedagogique.index();
    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int CUMULCREDIT = AttributesEnum.CumulCredit.index();
    public static final int DETTECREDIT = AttributesEnum.DetteCredit.index();
    public static final int IDINSCRIPTIONPEDSEMESTRE = AttributesEnum.IdInscriptionPedSemestre.index();
    public static final int IDSEMESTRE = AttributesEnum.IdSemestre.index();
    public static final int INSPEDVALIDE = AttributesEnum.InsPedValide.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InscPedSemRedoubleROVORowImpl() {
    }
}

