package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 24 08:46:23 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class isNivFormAccessAllowedRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdUtilisNiveauFormation {
            protected Object get(isNivFormAccessAllowedRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(isNivFormAccessAllowedRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Role {
            protected Object get(isNivFormAccessAllowedRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(isNivFormAccessAllowedRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(isNivFormAccessAllowedRowImpl object);

        protected abstract void put(isNivFormAccessAllowedRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDUTILISNIVEAUFORMATION = AttributesEnum.IdUtilisNiveauFormation.index();
    public static final int ROLE = AttributesEnum.Role.index();

    /**
     * This is the default constructor (do not remove).
     */
    public isNivFormAccessAllowedRowImpl() {
    }
}

