package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 07 11:36:08 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IsResponsableFilEcRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdUtilisFilierUeSemEc {
            protected Object get(IsResponsableFilEcRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(IsResponsableFilEcRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(IsResponsableFilEcRowImpl object);

        protected abstract void put(IsResponsableFilEcRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDUTILISFILIERUESEMEC = AttributesEnum.IdUtilisFilierUeSemEc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IsResponsableFilEcRowImpl() {
    }
}

