package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 08 17:44:30 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IsUserRespNivFormROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdUtilisNiveauFormation {
            protected Object get(IsUserRespNivFormROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(IsUserRespNivFormROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNiveauFormation {
            protected Object get(IsUserRespNivFormROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(IsUserRespNivFormROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(IsUserRespNivFormROVORowImpl object);

        protected abstract void put(IsUserRespNivFormROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDUTILISNIVEAUFORMATION = AttributesEnum.IdUtilisNiveauFormation.index();
    public static final int IDNIVEAUFORMATION = AttributesEnum.IdNiveauFormation.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IsUserRespNivFormROVORowImpl() {
    }
}

