package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 18 11:29:06 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListeInsPedIsAnnulDesistROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdInscriptionPedagogique {
            protected Object get(ListeInsPedIsAnnulDesistROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeInsPedIsAnnulDesistROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionAdmin {
            protected Object get(ListeInsPedIsAnnulDesistROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeInsPedIsAnnulDesistROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EtatInscrEtatInscrId {
            protected Object get(ListeInsPedIsAnnulDesistROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeInsPedIsAnnulDesistROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNiveauFormationParcours {
            protected Object get(ListeInsPedIsAnnulDesistROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeInsPedIsAnnulDesistROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetAnnee {
            protected Object get(ListeInsPedIsAnnulDesistROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeInsPedIsAnnulDesistROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibNivForm {
            protected Object get(ListeInsPedIsAnnulDesistROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeInsPedIsAnnulDesistROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibCourtNivForm {
            protected Object get(ListeInsPedIsAnnulDesistROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeInsPedIsAnnulDesistROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Libelle {
            protected Object get(ListeInsPedIsAnnulDesistROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeInsPedIsAnnulDesistROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibAnnee {
            protected Object get(ListeInsPedIsAnnulDesistROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeInsPedIsAnnulDesistROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdAnneesUnivers {
            protected Object get(ListeInsPedIsAnnulDesistROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeInsPedIsAnnulDesistROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(ListeInsPedIsAnnulDesistROVORowImpl object);

        protected abstract void put(ListeInsPedIsAnnulDesistROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDINSCRIPTIONPEDAGOGIQUE = AttributesEnum.IdInscriptionPedagogique.index();
    public static final int IDINSCRIPTIONADMIN = AttributesEnum.IdInscriptionAdmin.index();
    public static final int ETATINSCRETATINSCRID = AttributesEnum.EtatInscrEtatInscrId.index();
    public static final int IDNIVEAUFORMATIONPARCOURS = AttributesEnum.IdNiveauFormationParcours.index();
    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int LIBNIVFORM = AttributesEnum.LibNivForm.index();
    public static final int LIBCOURTNIVFORM = AttributesEnum.LibCourtNivForm.index();
    public static final int LIBELLE = AttributesEnum.Libelle.index();
    public static final int LIBANNEE = AttributesEnum.LibAnnee.index();
    public static final int IDANNEESUNIVERS = AttributesEnum.IdAnneesUnivers.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ListeInsPedIsAnnulDesistROVORowImpl() {
    }
}

