package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 06 13:14:09 GMT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListeEtudiantInscRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Numero {
            protected Object get(ListeEtudiantInscRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeEtudiantInscRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenomnom {
            protected Object get(ListeEtudiantInscRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeEtudiantInscRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionPedSemUe {
            protected Object get(ListeEtudiantInscRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ListeEtudiantInscRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(ListeEtudiantInscRowImpl object);

        protected abstract void put(ListeEtudiantInscRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int NUMERO = AttributesEnum.Numero.index();
    public static final int PRENOMNOM = AttributesEnum.Prenomnom.index();
    public static final int IDINSCRIPTIONPEDSEMUE = AttributesEnum.IdInscriptionPedSemUe.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ListeEtudiantInscRowImpl() {
    }
}

