package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 02 10:56:14 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MoisFinROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdMois {
            protected Object get(MoisFinROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(MoisFinROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleCourt {
            protected Object get(MoisFinROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(MoisFinROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(MoisFinROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(MoisFinROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(MoisFinROVORowImpl object);

        protected abstract void put(MoisFinROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDMOIS = AttributesEnum.IdMois.index();
    public static final int LIBELLECOURT = AttributesEnum.LibelleCourt.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MoisFinROVORowImpl() {
    }
}

