package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 02 09:27:16 UTC 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NiveauxSuperieursOptionsROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CodeNivSecSup {
            protected Object get(NiveauxSuperieursOptionsROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NiveauxSuperieursOptionsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OpCodeSup {
            protected Object get(NiveauxSuperieursOptionsROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NiveauxSuperieursOptionsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Nivsup {
            protected Object get(NiveauxSuperieursOptionsROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NiveauxSuperieursOptionsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Libelle {
            protected Object get(NiveauxSuperieursOptionsROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NiveauxSuperieursOptionsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(NiveauxSuperieursOptionsROVORowImpl object);

        protected abstract void put(NiveauxSuperieursOptionsROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CODENIVSECSUP = AttributesEnum.CodeNivSecSup.index();
    public static final int OPCODESUP = AttributesEnum.OpCodeSup.index();
    public static final int NIVSUP = AttributesEnum.Nivsup.index();
    public static final int LIBELLE = AttributesEnum.Libelle.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NiveauxSuperieursOptionsROVORowImpl() {
    }
}

