package model.readOnlyView;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 16 12:10:01 UTC 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NivFormSpecOptionROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        LibelleLong {
            protected Object get(NivFormSpecOptionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NivFormSpecOptionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNivFormSpecOption {
            protected Object get(NivFormSpecOptionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NivFormSpecOptionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNiveauFormationSpecialite {
            protected Object get(NivFormSpecOptionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NivFormSpecOptionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NivFormSpecialiteROVO {
            protected Object get(NivFormSpecOptionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NivFormSpecOptionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(NivFormSpecOptionROVORowImpl object);

        protected abstract void put(NivFormSpecOptionROVORowImpl object, Object value);

        protected int index() {
            return NivFormSpecOptionROVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return NivFormSpecOptionROVORowImpl.AttributesEnum.firstIndex() + NivFormSpecOptionROVORowImpl.AttributesEnum
                                                                                                          .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = NivFormSpecOptionROVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int IDNIVFORMSPECOPTION = AttributesEnum.IdNivFormSpecOption.index();
    public static final int IDNIVEAUFORMATIONSPECIALITE = AttributesEnum.IdNiveauFormationSpecialite.index();
    public static final int NIVFORMSPECIALITEROVO = AttributesEnum.NivFormSpecialiteROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NivFormSpecOptionROVORowImpl() {
    }
}

