package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 21 17:53:12 UTC 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NivFormSpecialiteLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NivFormSpecialiteLOVImpl() {
    }
}

