package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 12 15:34:34 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NivFormROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdNiveauFormation {
            protected Object get(NivFormROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NivFormROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleCourt {
            protected Object get(NivFormROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NivFormROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(NivFormROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NivFormROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdFormation {
            protected Object get(NivFormROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NivFormROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(NivFormROVORowImpl object);

        protected abstract void put(NivFormROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDNIVEAUFORMATION = AttributesEnum.IdNiveauFormation.index();
    public static final int LIBELLECOURT = AttributesEnum.LibelleCourt.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int IDFORMATION = AttributesEnum.IdFormation.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NivFormROVORowImpl() {
    }
}

