package model.readOnlyView;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 24 09:54:01 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NoteModeEnsGenAnonymROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdNoteModeEnseignement {
            protected Object get(NoteModeEnsGenAnonymROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NoteModeEnsGenAnonymROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Note {
            protected Object get(NoteModeEnsGenAnonymROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NoteModeEnsGenAnonymROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionPedSemUe {
            protected Object get(NoteModeEnsGenAnonymROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NoteModeEnsGenAnonymROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdTypeControle {
            protected Object get(NoteModeEnsGenAnonymROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NoteModeEnsGenAnonymROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(NoteModeEnsGenAnonymROVORowImpl object);

        protected abstract void put(NoteModeEnsGenAnonymROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDNOTEMODEENSEIGNEMENT = AttributesEnum.IdNoteModeEnseignement.index();
    public static final int NOTE = AttributesEnum.Note.index();
    public static final int IDINSCRIPTIONPEDSEMUE = AttributesEnum.IdInscriptionPedSemUe.index();
    public static final int IDTYPECONTROLE = AttributesEnum.IdTypeControle.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NoteModeEnsGenAnonymROVORowImpl() {
    }
}

