package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 04 14:40:14 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParcoursInfoROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdNiveauFormationParcours {
            protected Object get(ParcoursInfoROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursInfoROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibParcours {
            protected Object get(ParcoursInfoROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursInfoROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibOption {
            protected Object get(ParcoursInfoROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursInfoROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(ParcoursInfoROVORowImpl object);

        protected abstract void put(ParcoursInfoROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDNIVEAUFORMATIONPARCOURS = AttributesEnum.IdNiveauFormationParcours.index();
    public static final int LIBPARCOURS = AttributesEnum.LibParcours.index();
    public static final int LIBOPTION = AttributesEnum.LibOption.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ParcoursInfoROVORowImpl() {
    }
}

