package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 28 11:13:59 UTC 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParcoursSaisieModeCntrlROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdNiveauFormationParcours {
            protected Object get(ParcoursSaisieModeCntrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursSaisieModeCntrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdHistoriquesStructure {
            protected Object get(ParcoursSaisieModeCntrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursSaisieModeCntrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Niveauformationparcours {
            protected Object get(ParcoursSaisieModeCntrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursSaisieModeCntrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Responsablenivfr {
            protected Object get(ParcoursSaisieModeCntrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursSaisieModeCntrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Responsablefr {
            protected Object get(ParcoursSaisieModeCntrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursSaisieModeCntrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrcrsMaquetteAnROVO {
            protected Object get(ParcoursSaisieModeCntrlROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursSaisieModeCntrlROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(ParcoursSaisieModeCntrlROVORowImpl object);

        protected abstract void put(ParcoursSaisieModeCntrlROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDNIVEAUFORMATIONPARCOURS = AttributesEnum.IdNiveauFormationParcours.index();
    public static final int IDHISTORIQUESSTRUCTURE = AttributesEnum.IdHistoriquesStructure.index();
    public static final int NIVEAUFORMATIONPARCOURS = AttributesEnum.Niveauformationparcours.index();
    public static final int RESPONSABLENIVFR = AttributesEnum.Responsablenivfr.index();
    public static final int RESPONSABLEFR = AttributesEnum.Responsablefr.index();
    public static final int PRCRSMAQUETTEANROVO = AttributesEnum.PrcrsMaquetteAnROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ParcoursSaisieModeCntrlROVORowImpl() {
    }
}

