package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 10 11:04:58 UTC 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParcoursAttSpecialeROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdParcoursMaquetAnnee {
            protected Object get(ParcoursAttSpecialeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursAttSpecialeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNiveauFormationParcours {
            protected Object get(ParcoursAttSpecialeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursAttSpecialeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdUtilisateur {
            protected Object get(ParcoursAttSpecialeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursAttSpecialeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdAnneesUnivers {
            protected Object get(ParcoursAttSpecialeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursAttSpecialeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNiveau {
            protected Object get(ParcoursAttSpecialeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursAttSpecialeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Niveauformationparcours {
            protected Object get(ParcoursAttSpecialeROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcoursAttSpecialeROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected abstract Object get(ParcoursAttSpecialeROVORowImpl object);

        protected abstract void put(ParcoursAttSpecialeROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int IDNIVEAUFORMATIONPARCOURS = AttributesEnum.IdNiveauFormationParcours.index();
    public static final int IDUTILISATEUR = AttributesEnum.IdUtilisateur.index();
    public static final int IDANNEESUNIVERS = AttributesEnum.IdAnneesUnivers.index();
    public static final int IDNIVEAU = AttributesEnum.IdNiveau.index();
    public static final int NIVEAUFORMATIONPARCOURS = AttributesEnum.Niveauformationparcours.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ParcoursAttSpecialeROVORowImpl() {
    }
}

