package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 28 11:55:00 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParcrsParamModeSaisieECROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdMaquette {
            protected Object get(ParcrsParamModeSaisieECROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcrsParamModeSaisieECROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdAnneesUnivers {
            protected Object get(ParcrsParamModeSaisieECROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcrsParamModeSaisieECROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetAnnee {
            protected Object get(ParcrsParamModeSaisieECROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcrsParamModeSaisieECROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNiveau {
            protected Object get(ParcrsParamModeSaisieECROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcrsParamModeSaisieECROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Niveauformationparcours {
            protected Object get(ParcrsParamModeSaisieECROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcrsParamModeSaisieECROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Responsablenivfr {
            protected Object get(ParcrsParamModeSaisieECROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcrsParamModeSaisieECROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Responsablefr {
            protected Object get(ParcrsParamModeSaisieECROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcrsParamModeSaisieECROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FiliereUeSemestreROVO {
            protected Object get(ParcrsParamModeSaisieECROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcrsParamModeSaisieECROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AnneeUniverROVO1 {
            protected Object get(ParcrsParamModeSaisieECROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ParcrsParamModeSaisieECROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(ParcrsParamModeSaisieECROVORowImpl object);

        protected abstract void put(ParcrsParamModeSaisieECROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDMAQUETTE = AttributesEnum.IdMaquette.index();
    public static final int IDANNEESUNIVERS = AttributesEnum.IdAnneesUnivers.index();
    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int IDNIVEAU = AttributesEnum.IdNiveau.index();
    public static final int NIVEAUFORMATIONPARCOURS = AttributesEnum.Niveauformationparcours.index();
    public static final int RESPONSABLENIVFR = AttributesEnum.Responsablenivfr.index();
    public static final int RESPONSABLEFR = AttributesEnum.Responsablefr.index();
    public static final int FILIEREUESEMESTREROVO = AttributesEnum.FiliereUeSemestreROVO.index();
    public static final int ANNEEUNIVERROVO1 = AttributesEnum.AnneeUniverROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ParcrsParamModeSaisieECROVORowImpl() {
    }
}

