package model.readOnlyView;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 17 08:40:05 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersDejaAutoriserROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdAutorise {
            protected Object get(PersDejaAutoriserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(PersDejaAutoriserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateCreation {
            protected Object get(PersDejaAutoriserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(PersDejaAutoriserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateModification {
            protected Object get(PersDejaAutoriserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(PersDejaAutoriserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UtiCree {
            protected Object get(PersDejaAutoriserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(PersDejaAutoriserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UtiModifie {
            protected Object get(PersDejaAutoriserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(PersDejaAutoriserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Valide {
            protected Object get(PersDejaAutoriserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(PersDejaAutoriserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetAnnee {
            protected Object get(PersDejaAutoriserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(PersDejaAutoriserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdPersonne {
            protected Object get(PersDejaAutoriserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(PersDejaAutoriserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdAnneesUnivers {
            protected Object get(PersDejaAutoriserROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(PersDejaAutoriserROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(PersDejaAutoriserROVORowImpl object);

        protected abstract void put(PersDejaAutoriserROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDAUTORISE = AttributesEnum.IdAutorise.index();
    public static final int DATECREATION = AttributesEnum.DateCreation.index();
    public static final int DATEMODIFICATION = AttributesEnum.DateModification.index();
    public static final int UTICREE = AttributesEnum.UtiCree.index();
    public static final int UTIMODIFIE = AttributesEnum.UtiModifie.index();
    public static final int VALIDE = AttributesEnum.Valide.index();
    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int IDPERSONNE = AttributesEnum.IdPersonne.index();
    public static final int IDANNEESUNIVERS = AttributesEnum.IdAnneesUnivers.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PersDejaAutoriserROVORowImpl() {
    }
}

