package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 07 16:01:17 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PreinsApteEnRegleLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PreinsApteEnRegleLOVImpl() {
    }
}

