package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 12 11:17:53 UTC 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ResponsableUePrcrsMaqAnRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdUtilisateur {
            protected Object get(ResponsableUePrcrsMaqAnRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ResponsableUePrcrsMaqAnRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(ResponsableUePrcrsMaqAnRowImpl object);

        protected abstract void put(ResponsableUePrcrsMaqAnRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDUTILISATEUR = AttributesEnum.IdUtilisateur.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ResponsableUePrcrsMaqAnRowImpl() {
    }
}

