package model.readOnlyView;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 18 09:21:00 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScolFilUeRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        NbreEc {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CodificationUe {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CodeFiliereUeSemestre {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CodeSemestre {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreditUe {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Coefue {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CodeUe {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ResponsableId {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibLongUe {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibCategorieUe {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibCourtUe {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CodeCategorieUe {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prefixe {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Commentaire {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Fondamental {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibNature {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Compensable {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MoyenneValidation {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MoyenneEliminatoire {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CodeMatricule {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Emailucad {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CodeEtablissement {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ScolFilEc {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ScolProfesseur1 {
            protected Object get(ScolFilUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolFilUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(ScolFilUeRowImpl object);

        protected abstract void put(ScolFilUeRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int NBREEC = AttributesEnum.NbreEc.index();
    public static final int CODIFICATIONUE = AttributesEnum.CodificationUe.index();
    public static final int CODEFILIEREUESEMESTRE = AttributesEnum.CodeFiliereUeSemestre.index();
    public static final int CODESEMESTRE = AttributesEnum.CodeSemestre.index();
    public static final int CREDITUE = AttributesEnum.CreditUe.index();
    public static final int COEFUE = AttributesEnum.Coefue.index();
    public static final int CODEUE = AttributesEnum.CodeUe.index();
    public static final int RESPONSABLEID = AttributesEnum.ResponsableId.index();
    public static final int LIBLONGUE = AttributesEnum.LibLongUe.index();
    public static final int LIBCATEGORIEUE = AttributesEnum.LibCategorieUe.index();
    public static final int LIBCOURTUE = AttributesEnum.LibCourtUe.index();
    public static final int CODECATEGORIEUE = AttributesEnum.CodeCategorieUe.index();
    public static final int PREFIXE = AttributesEnum.Prefixe.index();
    public static final int COMMENTAIRE = AttributesEnum.Commentaire.index();
    public static final int FONDAMENTAL = AttributesEnum.Fondamental.index();
    public static final int LIBNATURE = AttributesEnum.LibNature.index();
    public static final int COMPENSABLE = AttributesEnum.Compensable.index();
    public static final int MOYENNEVALIDATION = AttributesEnum.MoyenneValidation.index();
    public static final int MOYENNEELIMINATOIRE = AttributesEnum.MoyenneEliminatoire.index();
    public static final int CODEMATRICULE = AttributesEnum.CodeMatricule.index();
    public static final int EMAILUCAD = AttributesEnum.Emailucad.index();
    public static final int CODEETABLISSEMENT = AttributesEnum.CodeEtablissement.index();
    public static final int SCOLFILEC = AttributesEnum.ScolFilEc.index();
    public static final int SCOLPROFESSEUR1 = AttributesEnum.ScolProfesseur1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ScolFilUeRowImpl() {
    }
}

