package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 01 12:31:29 UTC 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScolDeptDetailDapROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Code {
            protected Object get(ScolDeptDetailDapROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolDeptDetailDapROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(ScolDeptDetailDapROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolDeptDetailDapROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleCourt {
            protected Object get(ScolDeptDetailDapROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolDeptDetailDapROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EtablissemCode {
            protected Object get(ScolDeptDetailDapROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolDeptDetailDapROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Libelle {
            protected Object get(ScolDeptDetailDapROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolDeptDetailDapROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdStructure {
            protected Object get(ScolDeptDetailDapROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolDeptDetailDapROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ScolFormationIntegrationROVO {
            protected Object get(ScolDeptDetailDapROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ScolDeptDetailDapROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(ScolDeptDetailDapROVORowImpl object);

        protected abstract void put(ScolDeptDetailDapROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CODE = AttributesEnum.Code.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int LIBELLECOURT = AttributesEnum.LibelleCourt.index();
    public static final int ETABLISSEMCODE = AttributesEnum.EtablissemCode.index();
    public static final int LIBELLE = AttributesEnum.Libelle.index();
    public static final int IDSTRUCTURE = AttributesEnum.IdStructure.index();
    public static final int SCOLFORMATIONINTEGRATIONROVO = AttributesEnum.ScolFormationIntegrationROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ScolDeptDetailDapROVORowImpl() {
    }
}

