package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 18 09:36:27 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScolFilEcImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ScolFilEcImpl() {
    }
}

