package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 18 11:13:35 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScolStructureImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ScolStructureImpl() {
    }
}

