package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 12 14:23:06 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScolStudentInscDefImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ScolStudentInscDefImpl() {
    }
}

