package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 04 12:00:04 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StructureEtudBuROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StructureEtudBuROVOImpl() {
    }
}

