package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 15 08:13:49 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TypeValidationOperationLVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        valide {
            protected Object get(TypeValidationOperationLVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(TypeValidationOperationLVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        libelle_valide {
            protected Object get(TypeValidationOperationLVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(TypeValidationOperationLVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(TypeValidationOperationLVORowImpl object);

        protected abstract void put(TypeValidationOperationLVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int VALIDE = AttributesEnum.valide.index();
    public static final int LIBELLE_VALIDE = AttributesEnum.libelle_valide.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TypeValidationOperationLVORowImpl() {
    }
}

