package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 08 15:21:00 GMT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UeDelibROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UeDelibROVOImpl() {
    }


    /**
     * Returns the bind variable value for id_niv_form_parc.
     * @return bind variable value for id_niv_form_parc
     */
    public Long getid_niv_form_parc() {
        return (Long) getNamedWhereClauseParam("id_niv_form_parc");
    }

    /**
     * Sets <code>value</code> for bind variable id_niv_form_parc.
     * @param value value to bind as id_niv_form_parc
     */
    public void setid_niv_form_parc(Long value) {
        setNamedWhereClauseParam("id_niv_form_parc", value);
    }

    /**
     * Returns the bind variable value for id_util.
     * @return bind variable value for id_util
     */
    public Long getid_util() {
        return (Long) getNamedWhereClauseParam("id_util");
    }

    /**
     * Sets <code>value</code> for bind variable id_util.
     * @param value value to bind as id_util
     */
    public void setid_util(Long value) {
        setNamedWhereClauseParam("id_util", value);
    }

    /**
     * Returns the bind variable value for id_annee.
     * @return bind variable value for id_annee
     */
    public Long getid_annee() {
        return (Long) getNamedWhereClauseParam("id_annee");
    }

    /**
     * Sets <code>value</code> for bind variable id_annee.
     * @param value value to bind as id_annee
     */
    public void setid_annee(Long value) {
        setNamedWhereClauseParam("id_annee", value);
    }
}

