package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 14 12:53:15 CET 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UeNoteClosedDelibSemROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdFiliereUeSemstre {
            protected Object get(UeNoteClosedDelibSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(UeNoteClosedDelibSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Codification {
            protected Object get(UeNoteClosedDelibSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(UeNoteClosedDelibSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(UeNoteClosedDelibSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(UeNoteClosedDelibSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(UeNoteClosedDelibSemROVORowImpl object);

        protected abstract void put(UeNoteClosedDelibSemROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDFILIEREUESEMSTRE = AttributesEnum.IdFiliereUeSemstre.index();
    public static final int CODIFICATION = AttributesEnum.Codification.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UeNoteClosedDelibSemROVORowImpl() {
    }
}

