package model.readOnlyView;

import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 23 15:46:36 UTC 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UtilisateursROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdUtilisateur {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getIdUtilisateur();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenomnom {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getPrenomnom();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenoms {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getPrenoms();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenom {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getPrenom();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Nom {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getNom();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdStructure {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getIdStructure();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Etablissement {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getEtablissement();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleCourt {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getLibelleCourt();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Email {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getEmail();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        isSelected {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getisSelected();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setisSelected((Boolean) value);
            }
        }
        ,
        isUserSelected {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getisUserSelected();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setisUserSelected((Boolean) value);
            }
        }
        ,
        StructuresVO {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getStructuresVO();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UtilisateurNiveauFormationRO {
            protected Object get(UtilisateursROVORowImpl obj) {
                return obj.getUtilisateurNiveauFormationRO();
            }

            protected void put(UtilisateursROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(UtilisateursROVORowImpl object);

        protected abstract void put(UtilisateursROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDUTILISATEUR = AttributesEnum.IdUtilisateur.index();
    public static final int PRENOMNOM = AttributesEnum.Prenomnom.index();
    public static final int PRENOMS = AttributesEnum.Prenoms.index();
    public static final int PRENOM = AttributesEnum.Prenom.index();
    public static final int NOM = AttributesEnum.Nom.index();
    public static final int IDSTRUCTURE = AttributesEnum.IdStructure.index();
    public static final int ETABLISSEMENT = AttributesEnum.Etablissement.index();
    public static final int LIBELLECOURT = AttributesEnum.LibelleCourt.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int ISSELECTED = AttributesEnum.isSelected.index();
    public static final int ISUSERSELECTED = AttributesEnum.isUserSelected.index();
    public static final int STRUCTURESVO = AttributesEnum.StructuresVO.index();
    public static final int UTILISATEURNIVEAUFORMATIONRO = AttributesEnum.UtilisateurNiveauFormationRO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UtilisateursROVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute IdUtilisateur.
     * @return the IdUtilisateur
     */
    public Long getIdUtilisateur() {
        return (Long) getAttributeInternal(IDUTILISATEUR);
    }

    /**
     * Gets the attribute value for the calculated attribute Prenomnom.
     * @return the Prenomnom
     */
    public String getPrenomnom() {
        return (String) getAttributeInternal(PRENOMNOM);
    }

    /**
     * Gets the attribute value for the calculated attribute Prenoms.
     * @return the Prenoms
     */
    public String getPrenoms() {
        return (String) getAttributeInternal(PRENOMS);
    }

    /**
     * Gets the attribute value for the calculated attribute Prenom.
     * @return the Prenom
     */
    public String getPrenom() {
        return (String) getAttributeInternal(PRENOM);
    }

    /**
     * Gets the attribute value for the calculated attribute Nom.
     * @return the Nom
     */
    public String getNom() {
        return (String) getAttributeInternal(NOM);
    }

    /**
     * Gets the attribute value for the calculated attribute IdStructure.
     * @return the IdStructure
     */
    public Long getIdStructure() {
        return (Long) getAttributeInternal(IDSTRUCTURE);
    }

    /**
     * Gets the attribute value for the calculated attribute Etablissement.
     * @return the Etablissement
     */
    public String getEtablissement() {
        return (String) getAttributeInternal(ETABLISSEMENT);
    }

    /**
     * Gets the attribute value for the calculated attribute LibelleCourt.
     * @return the LibelleCourt
     */
    public String getLibelleCourt() {
        return (String) getAttributeInternal(LIBELLECOURT);
    }

    /**
     * Gets the attribute value for the calculated attribute Email.
     * @return the Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Gets the attribute value for the calculated attribute isSelected.
     * @return the isSelected
     */
    public Boolean getisSelected() {
        return (Boolean) getAttributeInternal(ISSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute isSelected.
     * @param value value to set the  isSelected
     */
    public void setisSelected(Boolean value) {
        setAttributeInternal(ISSELECTED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute isUserSelected.
     * @return the isUserSelected
     */
    public Boolean getisUserSelected() {
        return (Boolean) getAttributeInternal(ISUSERSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute isUserSelected.
     * @param value value to set the  isUserSelected
     */
    public void setisUserSelected(Boolean value) {
        setAttributeInternal(ISUSERSELECTED, value);
    }

    /**
     * Gets the associated <code>ViewRowImpl</code> using master-detail link StructuresVO.
     */
    public ViewRowImpl getStructuresVO() {
        return (ViewRowImpl) getAttributeInternal(STRUCTURESVO);
    }

    /**
     * Sets the master-detail link StructuresVO between this object and <code>value</code>.
     */
    public void setStructuresVO(ViewRowImpl value) {
        setAttributeInternal(STRUCTURESVO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UtilisateurNiveauFormationRO.
     */
    public RowIterator getUtilisateurNiveauFormationRO() {
        return (RowIterator) getAttributeInternal(UTILISATEURNIVEAUFORMATIONRO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

