package model.readOnlyView;

import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 25 16:34:58 UTC 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UtilisateurStructureVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdUtilisateur {
            protected Object get(UtilisateurStructureVORowImpl obj) {
                return obj.getIdUtilisateur();
            }

            protected void put(UtilisateurStructureVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Nom {
            protected Object get(UtilisateurStructureVORowImpl obj) {
                return obj.getNom();
            }

            protected void put(UtilisateurStructureVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenoms {
            protected Object get(UtilisateurStructureVORowImpl obj) {
                return obj.getPrenoms();
            }

            protected void put(UtilisateurStructureVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Prenomnom {
            protected Object get(UtilisateurStructureVORowImpl obj) {
                return obj.getPrenomnom();
            }

            protected void put(UtilisateurStructureVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AdressMail {
            protected Object get(UtilisateurStructureVORowImpl obj) {
                return obj.getAdressMail();
            }

            protected void put(UtilisateurStructureVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        isUserSelected {
            protected Object get(UtilisateurStructureVORowImpl obj) {
                return obj.getisUserSelected();
            }

            protected void put(UtilisateurStructureVORowImpl obj, Object value) {
                obj.setisUserSelected((Boolean) value);
            }
        }
        ,
        UtilisateursRolesVO {
            protected Object get(UtilisateurStructureVORowImpl obj) {
                return obj.getUtilisateursRolesVO();
            }

            protected void put(UtilisateurStructureVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UtilisateursFonctionnalitesVO {
            protected Object get(UtilisateurStructureVORowImpl obj) {
                return obj.getUtilisateursFonctionnalitesVO();
            }

            protected void put(UtilisateurStructureVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UtilisateursRolesVO1 {
            protected Object get(UtilisateurStructureVORowImpl obj) {
                return obj.getUtilisateursRolesVO1();
            }

            protected void put(UtilisateurStructureVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UtilisateursRolesROVO {
            protected Object get(UtilisateurStructureVORowImpl obj) {
                return obj.getUtilisateursRolesROVO();
            }

            protected void put(UtilisateurStructureVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(UtilisateurStructureVORowImpl object);

        protected abstract void put(UtilisateurStructureVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDUTILISATEUR = AttributesEnum.IdUtilisateur.index();
    public static final int NOM = AttributesEnum.Nom.index();
    public static final int PRENOMS = AttributesEnum.Prenoms.index();
    public static final int PRENOMNOM = AttributesEnum.Prenomnom.index();
    public static final int ADRESSMAIL = AttributesEnum.AdressMail.index();
    public static final int ISUSERSELECTED = AttributesEnum.isUserSelected.index();
    public static final int UTILISATEURSROLESVO = AttributesEnum.UtilisateursRolesVO.index();
    public static final int UTILISATEURSFONCTIONNALITESVO = AttributesEnum.UtilisateursFonctionnalitesVO.index();
    public static final int UTILISATEURSROLESVO1 = AttributesEnum.UtilisateursRolesVO1.index();
    public static final int UTILISATEURSROLESROVO = AttributesEnum.UtilisateursRolesROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UtilisateurStructureVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute IdUtilisateur.
     * @return the IdUtilisateur
     */
    public Long getIdUtilisateur() {
        return (Long) getAttributeInternal(IDUTILISATEUR);
    }

    /**
     * Gets the attribute value for the calculated attribute Nom.
     * @return the Nom
     */
    public String getNom() {
        return (String) getAttributeInternal(NOM);
    }

    /**
     * Gets the attribute value for the calculated attribute Prenoms.
     * @return the Prenoms
     */
    public String getPrenoms() {
        return (String) getAttributeInternal(PRENOMS);
    }

    /**
     * Gets the attribute value for the calculated attribute Prenomnom.
     * @return the Prenomnom
     */
    public String getPrenomnom() {
        return (String) getAttributeInternal(PRENOMNOM);
    }

    /**
     * Gets the attribute value for the calculated attribute AdressMail.
     * @return the AdressMail
     */
    public String getAdressMail() {
        return (String) getAttributeInternal(ADRESSMAIL);
    }

    /**
     * Gets the attribute value for the calculated attribute isUserSelected.
     * @return the isUserSelected
     */
    public Boolean getisUserSelected() {
        return (Boolean) getAttributeInternal(ISUSERSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute isUserSelected.
     * @param value value to set the  isUserSelected
     */
    public void setisUserSelected(Boolean value) {
        setAttributeInternal(ISUSERSELECTED, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UtilisateursRolesVO.
     */
    public RowIterator getUtilisateursRolesVO() {
        return (RowIterator) getAttributeInternal(UTILISATEURSROLESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UtilisateursFonctionnalitesVO.
     */
    public RowIterator getUtilisateursFonctionnalitesVO() {
        return (RowIterator) getAttributeInternal(UTILISATEURSFONCTIONNALITESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UtilisateursRolesVO1.
     */
    public RowIterator getUtilisateursRolesVO1() {
        return (RowIterator) getAttributeInternal(UTILISATEURSROLESVO1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UtilisateursRolesROVO.
     */
    public RowIterator getUtilisateursRolesROVO() {
        return (RowIterator) getAttributeInternal(UTILISATEURSROLESROVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

