package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 20 08:47:41 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExonerationEcolageROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ExonerationEcolageROVOImpl() {
    }
}

