package model.readOnlyView;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 18 12:31:44 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GroupeLingLangueROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdGrpLing {
            protected Object get(GroupeLingLangueROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GroupeLingLangueROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdGrpLingLangue {
            protected Object get(GroupeLingLangueROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GroupeLingLangueROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdLangue {
            protected Object get(GroupeLingLangueROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GroupeLingLangueROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleCourt {
            protected Object get(GroupeLingLangueROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GroupeLingLangueROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(GroupeLingLangueROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GroupeLingLangueROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LanguesVO1 {
            protected Object get(GroupeLingLangueROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(GroupeLingLangueROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(GroupeLingLangueROVORowImpl object);

        protected abstract void put(GroupeLingLangueROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDGRPLING = AttributesEnum.IdGrpLing.index();
    public static final int IDGRPLINGLANGUE = AttributesEnum.IdGrpLingLangue.index();
    public static final int IDLANGUE = AttributesEnum.IdLangue.index();
    public static final int LIBELLECOURT = AttributesEnum.LibelleCourt.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int LANGUESVO1 = AttributesEnum.LanguesVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GroupeLingLangueROVORowImpl() {
    }
}

