package model.readOnlyView;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 09 08:48:48 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RepartitionROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdRepartition {
            protected Object get(RepartitionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(RepartitionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdStructure {
            protected Object get(RepartitionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(RepartitionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleCourt {
            protected Object get(RepartitionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(RepartitionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(RepartitionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(RepartitionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Actif {
            protected Object get(RepartitionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(RepartitionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateDebut {
            protected Object get(RepartitionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(RepartitionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateFin {
            protected Object get(RepartitionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(RepartitionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdAnneesUnivers {
            protected Object get(RepartitionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(RepartitionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        case_cocher {
            protected Object get(RepartitionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(RepartitionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IsActive1 {
            protected Object get(RepartitionROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(RepartitionROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(RepartitionROVORowImpl object);

        protected abstract void put(RepartitionROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDREPARTITION = AttributesEnum.IdRepartition.index();
    public static final int IDSTRUCTURE = AttributesEnum.IdStructure.index();
    public static final int LIBELLECOURT = AttributesEnum.LibelleCourt.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int ACTIF = AttributesEnum.Actif.index();
    public static final int DATEDEBUT = AttributesEnum.DateDebut.index();
    public static final int DATEFIN = AttributesEnum.DateFin.index();
    public static final int IDANNEESUNIVERS = AttributesEnum.IdAnneesUnivers.index();
    public static final int CASE_COCHER = AttributesEnum.case_cocher.index();
    public static final int ISACTIVE1 = AttributesEnum.IsActive1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RepartitionROVORowImpl() {
    }
}

