package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 08 12:17:00 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InscPedEnCoursExcluROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdInscriptionPedagogique {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionAdmin {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNiveauFormationParcours {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetAnnee {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AsLibNivForm {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AsLibCourtNivForm {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DroitInsAdm {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DroitInsPed {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CoutFormation {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdAnneesUnivers {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EtatInscrEtatInscrId {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PieceIdentification {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdEtudiant {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdPaysNationalite {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdPersonne {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNiveau {
            protected Object get(InscPedEnCoursExcluROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscPedEnCoursExcluROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected abstract Object get(InscPedEnCoursExcluROVORowImpl object);

        protected abstract void put(InscPedEnCoursExcluROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDINSCRIPTIONPEDAGOGIQUE = AttributesEnum.IdInscriptionPedagogique.index();
    public static final int IDINSCRIPTIONADMIN = AttributesEnum.IdInscriptionAdmin.index();
    public static final int IDNIVEAUFORMATIONPARCOURS = AttributesEnum.IdNiveauFormationParcours.index();
    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int ASLIBNIVFORM = AttributesEnum.AsLibNivForm.index();
    public static final int ASLIBCOURTNIVFORM = AttributesEnum.AsLibCourtNivForm.index();
    public static final int DROITINSADM = AttributesEnum.DroitInsAdm.index();
    public static final int DROITINSPED = AttributesEnum.DroitInsPed.index();
    public static final int COUTFORMATION = AttributesEnum.CoutFormation.index();
    public static final int IDANNEESUNIVERS = AttributesEnum.IdAnneesUnivers.index();
    public static final int ETATINSCRETATINSCRID = AttributesEnum.EtatInscrEtatInscrId.index();
    public static final int PIECEIDENTIFICATION = AttributesEnum.PieceIdentification.index();
    public static final int IDETUDIANT = AttributesEnum.IdEtudiant.index();
    public static final int IDPAYSNATIONALITE = AttributesEnum.IdPaysNationalite.index();
    public static final int IDPERSONNE = AttributesEnum.IdPersonne.index();
    public static final int IDNIVEAU = AttributesEnum.IdNiveau.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InscPedEnCoursExcluROVORowImpl() {
    }
}

