package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 04 10:43:48 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class isSess1ClosedImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public isSess1ClosedImpl() {
    }
}

