package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 28 10:55:44 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getInsPedSemImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public getInsPedSemImpl() {
    }
}

