package model.readOnlyView;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 08 11:55:44 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FilEcInsPedSemUeRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdFiliereUeSemstreEc {
            protected Object get(FilEcInsPedSemUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FilEcInsPedSemUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(FilEcInsPedSemUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FilEcInsPedSemUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionPedSemUe {
            protected Object get(FilEcInsPedSemUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FilEcInsPedSemUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Coefficient {
            protected Object get(FilEcInsPedSemUeRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(FilEcInsPedSemUeRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(FilEcInsPedSemUeRowImpl object);

        protected abstract void put(FilEcInsPedSemUeRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDFILIEREUESEMSTREEC = AttributesEnum.IdFiliereUeSemstreEc.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int IDINSCRIPTIONPEDSEMUE = AttributesEnum.IdInscriptionPedSemUe.index();
    public static final int COEFFICIENT = AttributesEnum.Coefficient.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FilEcInsPedSemUeRowImpl() {
    }
}

