package model.readOnlyView;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 20 08:47:41 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExonerationEcolageROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdAnneesUnivers {
            protected Object get(ExonerationEcolageROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExonerationEcolageROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdExoneration {
            protected Object get(ExonerationEcolageROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExonerationEcolageROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionPedagogique {
            protected Object get(ExonerationEcolageROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExonerationEcolageROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdMotifExoneration {
            protected Object get(ExonerationEcolageROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExonerationEcolageROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNatureExoneration {
            protected Object get(ExonerationEcolageROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExonerationEcolageROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdTypeExoneration {
            protected Object get(ExonerationEcolageROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExonerationEcolageROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Montant {
            protected Object get(ExonerationEcolageROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExonerationEcolageROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RefExo {
            protected Object get(ExonerationEcolageROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExonerationEcolageROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Taux {
            protected Object get(ExonerationEcolageROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ExonerationEcolageROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(ExonerationEcolageROVORowImpl object);

        protected abstract void put(ExonerationEcolageROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDANNEESUNIVERS = AttributesEnum.IdAnneesUnivers.index();
    public static final int IDEXONERATION = AttributesEnum.IdExoneration.index();
    public static final int IDINSCRIPTIONPEDAGOGIQUE = AttributesEnum.IdInscriptionPedagogique.index();
    public static final int IDMOTIFEXONERATION = AttributesEnum.IdMotifExoneration.index();
    public static final int IDNATUREEXONERATION = AttributesEnum.IdNatureExoneration.index();
    public static final int IDTYPEEXONERATION = AttributesEnum.IdTypeExoneration.index();
    public static final int MONTANT = AttributesEnum.Montant.index();
    public static final int REFEXO = AttributesEnum.RefExo.index();
    public static final int TAUX = AttributesEnum.Taux.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ExonerationEcolageROVORowImpl() {
    }
}

