package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 14 16:14:03 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IsValidationFilEcExistImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IsValidationFilEcExistImpl() {
    }
}

