package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 18 16:40:12 GMT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AttributSearchROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        LibForm {
            protected Object get(AttributSearchROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AttributSearchROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Niveau {
            protected Object get(AttributSearchROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AttributSearchROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(AttributSearchROVORowImpl object);

        protected abstract void put(AttributSearchROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LIBFORM = AttributesEnum.LibForm.index();
    public static final int NIVEAU = AttributesEnum.Niveau.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AttributSearchROVORowImpl() {
    }
}

