package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 11 09:16:49 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InscPedSemRedoubleROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InscPedSemRedoubleROVOImpl() {
    }
}

