package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 26 20:22:18 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AnonymatExecuteROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AnonymatExecuteROVOImpl() {
    }

    /**
     * Returns the bind variable value for parcours.
     * @return bind variable value for parcours
     */
    public Long getparcours() {
        return (Long) getNamedWhereClauseParam("parcours");
    }

    /**
     * Sets <code>value</code> for bind variable parcours.
     * @param value value to bind as parcours
     */
    public void setparcours(Long value) {
        setNamedWhereClauseParam("parcours", value);
    }

    /**
     * Returns the bind variable value for semestre.
     * @return bind variable value for semestre
     */
    public Long getsemestre() {
        return (Long) getNamedWhereClauseParam("semestre");
    }

    /**
     * Sets <code>value</code> for bind variable semestre.
     * @param value value to bind as semestre
     */
    public void setsemestre(Long value) {
        setNamedWhereClauseParam("semestre", value);
    }

    /**
     * Returns the bind variable value for sessions.
     * @return bind variable value for sessions
     */
    public Long getsessions() {
        return (Long) getNamedWhereClauseParam("sessions");
    }

    /**
     * Sets <code>value</code> for bind variable sessions.
     * @param value value to bind as sessions
     */
    public void setsessions(Long value) {
        setNamedWhereClauseParam("sessions", value);
    }

    /**
     * Returns the bind variable value for anne.
     * @return bind variable value for anne
     */
    public Long getanne() {
        return (Long) getNamedWhereClauseParam("anne");
    }

    /**
     * Sets <code>value</code> for bind variable anne.
     * @param value value to bind as anne
     */
    public void setanne(Long value) {
        setNamedWhereClauseParam("anne", value);
    }
}

