package model.readOnlyView.common;

import java.lang.Integer;
import java.lang.Long;
import java.lang.String;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.SQLException;
import java.sql.Timestamp;

import oracle.jbo.JboException;
import oracle.jbo.StructureDef;
import oracle.jbo.domain.DatumFactory;
import oracle.jbo.domain.DomainAttributeDef;
import oracle.jbo.domain.DomainInterface;
import oracle.jbo.domain.DomainOwnerInterface;
import oracle.jbo.domain.DomainStructureDef;
import oracle.jbo.domain.Struct;

import oracle.sql.*;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 07 12:32:09 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TypePreinscrp extends Struct {
    static ORADataFactory[] mCustDatFac = null;
    static int[] mSQLTypes = null;
    static DomainStructureDef mStructureDef = null;
    static ORADataFactory fac;

    public TypePreinscrp(Datum value) throws SQLException {
        super(value);
    }

    public TypePreinscrp() throws SQLException {
    }

    public static ORADataFactory getORADataFactory() {
        if (fac == null) {
            class facClass implements ORADataFactory {
                public ORAData create(Datum d, int sql_type_code) throws SQLException {
                    if (d != null) {
                        return new TypePreinscrp(d);
                    }
                    return null;
                }
            }
            fac = new facClass();
        }
        return fac;
    }

    public int[] getAttrSQLTypes() {
        if (mSQLTypes == null) {
            mSQLTypes = buildAttrSQLTypes();
        }
        return mSQLTypes;
    }

    public StructureDef getStructureDef() {
        return mStructureDef;
    }

    public String getColumnType() {
        return "TYPE_PREINSCRP";
    }

    public Long getIdEtudiant() {
        return (Long) getAttribute(0);
    }

    public void setIdEtudiant(Long value) {
        setAttribute(0, value);
    }

    public String getNumero() {
        return (String) getAttribute(1);
    }

    public void setNumero(String value) {
        setAttribute(1, value);
    }

    public String getAdresse() {
        return (String) getAttribute(2);
    }

    public void setAdresse(String value) {
        setAttribute(2, value);
    }

    public Timestamp getDateNaissance() {
        return (Timestamp) getAttribute(3);
    }

    public void setDateNaissance(Timestamp value) {
        setAttribute(3, value);
    }

    public Long getIdPersonne() {
        return (Long) getAttribute(4);
    }

    public void setIdPersonne(Long value) {
        setAttribute(4, value);
    }

    public String getLieuNaissance() {
        return (String) getAttribute(5);
    }

    public void setLieuNaissance(String value) {
        setAttribute(5, value);
    }

    public String getNom() {
        return (String) getAttribute(6);
    }

    public void setNom(String value) {
        setAttribute(6, value);
    }

    public String getPieceIdentification() {
        return (String) getAttribute(7);
    }

    public void setPieceIdentification(String value) {
        setAttribute(7, value);
    }

    public String getPrenoms() {
        return (String) getAttribute(8);
    }

    public void setPrenoms(String value) {
        setAttribute(8, value);
    }

    public Integer getEtatInscrEtatInscrId() {
        return (Integer) getAttribute(9);
    }

    public void setEtatInscrEtatInscrId(Integer value) {
        setAttribute(9, value);
    }

    public Long getIdInscriptionPedagogique() {
        return (Long) getAttribute(10);
    }

    public void setIdInscriptionPedagogique(Long value) {
        setAttribute(10, value);
    }

    public Long getIdInscriptionAdmin() {
        return (Long) getAttribute(11);
    }

    public void setIdInscriptionAdmin(Long value) {
        setAttribute(11, value);
    }

    public Long getIdParcoursMaquetAnnee() {
        return (Long) getAttribute(12);
    }

    public void setIdParcoursMaquetAnnee(Long value) {
        setAttribute(12, value);
    }

    public Integer getInsEnLigne() {
        return (Integer) getAttribute(13);
    }

    public void setInsEnLigne(Integer value) {
        setAttribute(13, value);
    }

    public Integer getEtudBuEnRegle() {
        return (Integer) getAttribute(14);
    }

    public void setEtudBuEnRegle(Integer value) {
        setAttribute(14, value);
    }

    public Integer getEtudApp() {
        return (Integer) getAttribute(15);
    }

    public void setEtudApp(Integer value) {
        setAttribute(15, value);
    }

    public void initStructureDef() {
        DomainAttributeDef[] attrs = new DomainAttributeDef[16];
        if (mStructureDef == null) {
            attrs[0] = new DomainAttributeDef("IdEtudiant", "ID_ETUDIANT", 0, Long.class, 2, "NUMERIC", 0, 10, false);
            attrs[1] = new DomainAttributeDef("Numero", "NUMERO", 1, String.class, 12, "VARCHAR", -127, 50, false);
            attrs[2] = new DomainAttributeDef("Adresse", "ADRESSE", 2, String.class, 12, "VARCHAR", -127, 200, false);
            attrs[3] =
                new DomainAttributeDef("DateNaissance", "DATE_NAISSANCE", 3, Timestamp.class, 91, "DATE", -127, 0,
                                       false);
            attrs[4] = new DomainAttributeDef("IdPersonne", "ID_PERSONNE", 4, Long.class, 2, "NUMERIC", 0, 10, false);
            attrs[5] =
                new DomainAttributeDef("LieuNaissance", "LIEU_NAISSANCE", 5, String.class, 12, "VARCHAR", -127, 200,
                                       false);
            attrs[6] = new DomainAttributeDef("Nom", "NOM", 6, String.class, 12, "VARCHAR", -127, 100, false);
            attrs[7] =
                new DomainAttributeDef("PieceIdentification", "PIECE_IDENTIFICATION", 7, String.class, 12, "VARCHAR",
                                       -127, 50, false);
            attrs[8] = new DomainAttributeDef("Prenoms", "PRENOMS", 8, String.class, 12, "VARCHAR", -127, 200, false);
            attrs[9] =
                new DomainAttributeDef("EtatInscrEtatInscrId", "ETAT_INSCR_ETAT_INSCR_ID", 9, Integer.class, 2,
                                       "NUMERIC", 0, 5, false);
            attrs[10] =
                new DomainAttributeDef("IdInscriptionPedagogique", "ID_INSCRIPTION_PEDAGOGIQUE", 10, Long.class, 2,
                                       "NUMERIC", 0, 10, false);
            attrs[11] =
                new DomainAttributeDef("IdInscriptionAdmin", "ID_INSCRIPTION_ADMIN", 11, Long.class, 2, "NUMERIC", 0,
                                       10, false);
            attrs[12] =
                new DomainAttributeDef("IdParcoursMaquetAnnee", "ID_PARCOURS_MAQUET_ANNEE", 12, Long.class, 2,
                                       "NUMERIC", 0, 10, false);
            attrs[13] =
                new DomainAttributeDef("InsEnLigne", "INS_EN_LIGNE", 13, Integer.class, 2, "NUMERIC", 0, 1, false);
            attrs[14] =
                new DomainAttributeDef("EtudBuEnRegle", "ETUD_BU_EN_REGLE", 14, Integer.class, 2, "NUMERIC", 0, 1,
                                       false);
            attrs[15] = new DomainAttributeDef("EtudApp", "ETUD_APP", 15, Integer.class, 2, "NUMERIC", 0, 1, false);
            mStructureDef = new DomainStructureDef(attrs);
        }
    }

    public ORADataFactory[] getAttrORADataFactories() {
        if (mCustDatFac == null) {
            mCustDatFac = new ORADataFactory[16];
            mCustDatFac[0] = null;
            mCustDatFac[1] = null;
            mCustDatFac[2] = null;
            mCustDatFac[3] = null;
            mCustDatFac[4] = null;
            mCustDatFac[5] = null;
            mCustDatFac[6] = null;
            mCustDatFac[7] = null;
            mCustDatFac[8] = null;
            mCustDatFac[9] = null;
            mCustDatFac[10] = null;
            mCustDatFac[11] = null;
            mCustDatFac[12] = null;
            mCustDatFac[13] = null;
            mCustDatFac[14] = null;
            mCustDatFac[15] = null;
        }
        return mCustDatFac;
    }
}

