package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 03 11:26:14 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllInteFilEcROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdTypeControle {
            protected Object get(AllInteFilEcROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AllInteFilEcROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdModeControleEc {
            protected Object get(AllInteFilEcROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(AllInteFilEcROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(AllInteFilEcROVORowImpl object);

        protected abstract void put(AllInteFilEcROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDTYPECONTROLE = AttributesEnum.IdTypeControle.index();
    public static final int IDMODECONTROLEEC = AttributesEnum.IdModeControleEc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AllInteFilEcROVORowImpl() {
    }
}

