package model.entities;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 21 13:47:59 CET 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NotesModeEnseignementInterEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdNoteModeEnsInter {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionPedSemUe {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdModeControleEc {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdTypeVerrou {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdTypeControle {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdCalendrierDeliberation {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Note {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateCreation {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateModification {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UtiCree {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UtiModifie {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Valide {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IsAbsent {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Style {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EtudiantInscrisROVO {
            protected Object get(NotesModeEnseignementInterEOImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NotesModeEnseignementInterEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(NotesModeEnseignementInterEOImpl object);

        protected abstract void put(NotesModeEnseignementInterEOImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDNOTEMODEENSINTER = AttributesEnum.IdNoteModeEnsInter.index();
    public static final int IDINSCRIPTIONPEDSEMUE = AttributesEnum.IdInscriptionPedSemUe.index();
    public static final int IDMODECONTROLEEC = AttributesEnum.IdModeControleEc.index();
    public static final int IDTYPEVERROU = AttributesEnum.IdTypeVerrou.index();
    public static final int IDTYPECONTROLE = AttributesEnum.IdTypeControle.index();
    public static final int IDCALENDRIERDELIBERATION = AttributesEnum.IdCalendrierDeliberation.index();
    public static final int NOTE = AttributesEnum.Note.index();
    public static final int DATECREATION = AttributesEnum.DateCreation.index();
    public static final int DATEMODIFICATION = AttributesEnum.DateModification.index();
    public static final int UTICREE = AttributesEnum.UtiCree.index();
    public static final int UTIMODIFIE = AttributesEnum.UtiModifie.index();
    public static final int VALIDE = AttributesEnum.Valide.index();
    public static final int ISABSENT = AttributesEnum.IsAbsent.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int ETUDIANTINSCRISROVO = AttributesEnum.EtudiantInscrisROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NotesModeEnseignementInterEOImpl() {
    }

    /**
     * @param idNoteModeEnsInter key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Long idNoteModeEnsInter) {
        return new Key(new Object[] { idNoteModeEnsInter });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.entities.NotesModeEnseignementInterEO");
    }


}

