package model.readOnlyView;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 16 12:54:14 GMT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InscriptPedSemROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdSemestre {
            protected Object get(InscriptPedSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscriptPedSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(InscriptPedSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscriptPedSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleCourt {
            protected Object get(InscriptPedSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscriptPedSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleEnLettre {
            protected Object get(InscriptPedSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscriptPedSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Rang {
            protected Object get(InscriptPedSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscriptPedSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Ordre {
            protected Object get(InscriptPedSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscriptPedSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateCreation {
            protected Object get(InscriptPedSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscriptPedSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DateModification {
            protected Object get(InscriptPedSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscriptPedSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UtiCree {
            protected Object get(InscriptPedSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscriptPedSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UtiModifie {
            protected Object get(InscriptPedSemROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InscriptPedSemROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(InscriptPedSemROVORowImpl object);

        protected abstract void put(InscriptPedSemROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDSEMESTRE = AttributesEnum.IdSemestre.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int LIBELLECOURT = AttributesEnum.LibelleCourt.index();
    public static final int LIBELLEENLETTRE = AttributesEnum.LibelleEnLettre.index();
    public static final int RANG = AttributesEnum.Rang.index();
    public static final int ORDRE = AttributesEnum.Ordre.index();
    public static final int DATECREATION = AttributesEnum.DateCreation.index();
    public static final int DATEMODIFICATION = AttributesEnum.DateModification.index();
    public static final int UTICREE = AttributesEnum.UtiCree.index();
    public static final int UTIMODIFIE = AttributesEnum.UtiModifie.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InscriptPedSemROVORowImpl() {
    }
}

