package model.updatableview;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 23 09:24:21 UTC 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NotesModeEnseignementInterVO1Impl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NotesModeEnseignementInterVO1Impl() {
    }

    /**
     * Returns the bind variable value for id_cal_delib_var.
     * @return bind variable value for id_cal_delib_var
     */
    public Long getid_cal_delib_var() {
        return (Long) getNamedWhereClauseParam("id_cal_delib_var");
    }

    /**
     * Sets <code>value</code> for bind variable id_cal_delib_var.
     * @param value value to bind as id_cal_delib_var
     */
    public void setid_cal_delib_var(Long value) {
        setNamedWhereClauseParam("id_cal_delib_var", value);
    }

    /**
     * Returns the bind variable value for id_mode_ctrl_ec_var.
     * @return bind variable value for id_mode_ctrl_ec_var
     */
    public Long getid_mode_ctrl_ec_var() {
        return (Long) getNamedWhereClauseParam("id_mode_ctrl_ec_var");
    }

    /**
     * Sets <code>value</code> for bind variable id_mode_ctrl_ec_var.
     * @param value value to bind as id_mode_ctrl_ec_var
     */
    public void setid_mode_ctrl_ec_var(Long value) {
        setNamedWhereClauseParam("id_mode_ctrl_ec_var", value);
    }

    /**
     * Returns the bind variable value for id_type_ctrl_var.
     * @return bind variable value for id_type_ctrl_var
     */
    public Long getid_type_ctrl_var() {
        return (Long) getNamedWhereClauseParam("id_type_ctrl_var");
    }

    /**
     * Sets <code>value</code> for bind variable id_type_ctrl_var.
     * @param value value to bind as id_type_ctrl_var
     */
    public void setid_type_ctrl_var(Long value) {
        setNamedWhereClauseParam("id_type_ctrl_var", value);
    }
}

