package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 19 11:34:20 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IsFormationTextIsImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IsFormationTextIsImpl() {
    }
}

