package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 30 14:29:27 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ResultParcoursSupROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdParcoursMaquetAnnee {
            protected Object get(ResultParcoursSupROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ResultParcoursSupROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNiveauFormationParcours {
            protected Object get(ResultParcoursSupROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ResultParcoursSupROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibNivForm {
            protected Object get(ResultParcoursSupROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ResultParcoursSupROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibCourtNivForm {
            protected Object get(ResultParcoursSupROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ResultParcoursSupROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNivForm {
            protected Object get(ResultParcoursSupROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ResultParcoursSupROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdNiveau {
            protected Object get(ResultParcoursSupROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ResultParcoursSupROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Niveau {
            protected Object get(ResultParcoursSupROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(ResultParcoursSupROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(ResultParcoursSupROVORowImpl object);

        protected abstract void put(ResultParcoursSupROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int IDNIVEAUFORMATIONPARCOURS = AttributesEnum.IdNiveauFormationParcours.index();
    public static final int LIBNIVFORM = AttributesEnum.LibNivForm.index();
    public static final int LIBCOURTNIVFORM = AttributesEnum.LibCourtNivForm.index();
    public static final int IDNIVFORM = AttributesEnum.IdNivForm.index();
    public static final int IDNIVEAU = AttributesEnum.IdNiveau.index();
    public static final int NIVEAU = AttributesEnum.Niveau.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ResultParcoursSupROVORowImpl() {
    }
}

