package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 11 10:53:03 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InfoExonerationROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EtatInscrEtatInscrId {
            protected Object get(InfoExonerationROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InfoExonerationROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionPedagogique {
            protected Object get(InfoExonerationROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InfoExonerationROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdParcoursMaquetAnnee {
            protected Object get(InfoExonerationROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InfoExonerationROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CoutFormation {
            protected Object get(InfoExonerationROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InfoExonerationROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DroitInsAdm {
            protected Object get(InfoExonerationROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InfoExonerationROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DroitInsPed {
            protected Object get(InfoExonerationROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InfoExonerationROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibForm {
            protected Object get(InfoExonerationROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InfoExonerationROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibAnnee {
            protected Object get(InfoExonerationROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(InfoExonerationROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(InfoExonerationROVORowImpl object);

        protected abstract void put(InfoExonerationROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ETATINSCRETATINSCRID = AttributesEnum.EtatInscrEtatInscrId.index();
    public static final int IDINSCRIPTIONPEDAGOGIQUE = AttributesEnum.IdInscriptionPedagogique.index();
    public static final int IDPARCOURSMAQUETANNEE = AttributesEnum.IdParcoursMaquetAnnee.index();
    public static final int COUTFORMATION = AttributesEnum.CoutFormation.index();
    public static final int DROITINSADM = AttributesEnum.DroitInsAdm.index();
    public static final int DROITINSPED = AttributesEnum.DroitInsPed.index();
    public static final int LIBFORM = AttributesEnum.LibForm.index();
    public static final int LIBANNEE = AttributesEnum.LibAnnee.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InfoExonerationROVORowImpl() {
    }
}

