package model.updatableview.common;

import java.lang.String;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.SQLException;

import oracle.jbo.JboException;
import oracle.jbo.StructureDef;
import oracle.jbo.domain.Array;
import oracle.jbo.domain.DatumFactory;
import oracle.jbo.domain.DomainAttributeDef;
import oracle.jbo.domain.DomainInterface;
import oracle.jbo.domain.DomainOwnerInterface;
import oracle.jbo.domain.DomainStructureDef;
import oracle.jbo.domain.Struct;

import oracle.sql.*;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 02 16:02:56 UTC 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TableEtudiantsemestre extends Struct {
    static ORADataFactory[] mCustDatFac = null;
    static int[] mSQLTypes = null;
    static DomainStructureDef mStructureDef = null;
    static ORADataFactory fac;

    public TableEtudiantsemestre(Datum value) throws SQLException {
        super(value);
    }

    public TableEtudiantsemestre() throws SQLException {
    }

    public static ORADataFactory getORADataFactory() {
        if (fac == null) {
            class facClass implements ORADataFactory {
                public ORAData create(Datum d, int sql_type_code) throws SQLException {
                    if (d != null) {
                        return new TableEtudiantsemestre(d);
                    }
                    return null;
                }
            }
            fac = new facClass();
        }
        return fac;
    }

    public int[] getAttrSQLTypes() {
        if (mSQLTypes == null) {
            mSQLTypes = buildAttrSQLTypes();
        }
        return mSQLTypes;
    }

    public StructureDef getStructureDef() {
        return mStructureDef;
    }

    public String getColumnType() {
        return "TABLE_ETUDIANTSEMESTRE";
    }

    public String getnumero() {
        return (String) getAttribute(0);
    }

    public void setnumero(String value) {
        setAttribute(0, value);
    }

    public String getprenom_nom() {
        return (String) getAttribute(1);
    }

    public void setprenom_nom(String value) {
        setAttribute(1, value);
    }

    public Array getsemestre() {
        return (Array) getAttribute(2);
    }

    public void setsemestre(Array value) {
        setAttribute(2, value);
    }

    public String getmoyenne() {
        return (String) getAttribute(3);
    }

    public void setmoyenne(String value) {
        setAttribute(3, value);
    }


    public void initStructureDef() {
        DomainAttributeDef[] attrs = new DomainAttributeDef[4];
        if (mStructureDef == null) {
            attrs[0] = new DomainAttributeDef("numero", "NUMERO", 0, String.class, 12, "VARCHAR", -127, 255, false);
            attrs[1] =
                new DomainAttributeDef("prenom_nom", "PRENOM_NOM", 1, String.class, 12, "VARCHAR", -127, 255, false);
            attrs[2] = new DomainAttributeDef("semestre", "SEMESTRE", 2, Array.class, 2002, "STRUCT", -127, 0, false);
            attrs[3] = new DomainAttributeDef("moyenne", "MOYENNE", 3, String.class, 12, "VARCHAR", -127, 255, false);
            mStructureDef = new DomainStructureDef(attrs);
        }
    }

    public ORADataFactory[] getAttrORADataFactories() {
        if (mCustDatFac == null) {
            mCustDatFac = new ORADataFactory[4];
            mCustDatFac[0] = null;
            mCustDatFac[1] = null;
            mCustDatFac[2] = Array.getORADataFactory();
            mCustDatFac[3] = null;
        }
        return mCustDatFac;
    }
}

