package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 09 12:52:45 GMT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class reInscripAdminROVO2RowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdInscriptionPedagogique {
            protected Object get(reInscripAdminROVO2RowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(reInscripAdminROVO2RowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionPedSemestre {
            protected Object get(reInscripAdminROVO2RowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(reInscripAdminROVO2RowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdSemestre {
            protected Object get(reInscripAdminROVO2RowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(reInscripAdminROVO2RowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdInscriptionAdmin {
            protected Object get(reInscripAdminROVO2RowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(reInscripAdminROVO2RowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(reInscripAdminROVO2RowImpl object);

        protected abstract void put(reInscripAdminROVO2RowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDINSCRIPTIONPEDAGOGIQUE = AttributesEnum.IdInscriptionPedagogique.index();
    public static final int IDINSCRIPTIONPEDSEMESTRE = AttributesEnum.IdInscriptionPedSemestre.index();
    public static final int IDSEMESTRE = AttributesEnum.IdSemestre.index();
    public static final int IDINSCRIPTIONADMIN = AttributesEnum.IdInscriptionAdmin.index();

    /**
     * This is the default constructor (do not remove).
     */
    public reInscripAdminROVO2RowImpl() {
    }
}

