package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 15 16:17:31 GMT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DelibSemRepCritereCompLOVRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        code {
            protected Object get(DelibSemRepCritereCompLOVRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemRepCritereCompLOVRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        libelle {
            protected Object get(DelibSemRepCritereCompLOVRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DelibSemRepCritereCompLOVRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(DelibSemRepCritereCompLOVRowImpl object);

        protected abstract void put(DelibSemRepCritereCompLOVRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CODE = AttributesEnum.code.index();
    public static final int LIBELLE = AttributesEnum.libelle.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DelibSemRepCritereCompLOVRowImpl() {
    }
}

