package model.readOnlyView;

import java.math.BigDecimal;

import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 14 09:29:49 UTC 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EtudiantResultAnnuelDelibROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EtudiantResultAnnuelDelibROVOImpl() {
    }

    /**
     * Returns the bind variable value for annee.
     * @return bind variable value for annee
     */
    public Integer getannee() {
        return (Integer) getNamedWhereClauseParam("annee");
    }

    /**
     * Sets <code>value</code> for bind variable annee.
     * @param value value to bind as annee
     */
    public void setannee(Integer value) {
        setNamedWhereClauseParam("annee", value);
    }

    /**
     * Returns the bind variable value for parcours.
     * @return bind variable value for parcours
     */
    public Integer getparcours() {
        return (Integer) getNamedWhereClauseParam("parcours");
    }

    /**
     * Sets <code>value</code> for bind variable parcours.
     * @param value value to bind as parcours
     */
    public void setparcours(Integer value) {
        setNamedWhereClauseParam("parcours", value);
    }


    /**
     * Returns the variable value for cred1.
     * @return variable value for cred1
     */
    public Number getcred1() {
        return (Number) ensureVariableManager().getVariableValue("cred1");
    }

    /**
     * Sets <code>value</code> for variable cred1.
     * @param value value to bind as cred1
     */
    public void setcred1(Number value) {
        ensureVariableManager().setVariableValue("cred1", value);
    }

    /**
     * Returns the variable value for cred2.
     * @return variable value for cred2
     */
    public Number getcred2() {
        return (Number) ensureVariableManager().getVariableValue("cred2");
    }

    /**
     * Sets <code>value</code> for variable cred2.
     * @param value value to bind as cred2
     */
    public void setcred2(Number value) {
        ensureVariableManager().setVariableValue("cred2", value);
    }

    /**
     * Returns the variable value for moy1.
     * @return variable value for moy1
     */
    public Number getmoy1() {
        return (Number) ensureVariableManager().getVariableValue("moy1");
    }

    /**
     * Sets <code>value</code> for variable moy1.
     * @param value value to bind as moy1
     */
    public void setmoy1(Number value) {
        ensureVariableManager().setVariableValue("moy1", value);
    }

    /**
     * Returns the variable value for moy2.
     * @return variable value for moy2
     */
    public Number getmoy2() {
        return (Number) ensureVariableManager().getVariableValue("moy2");
    }

    /**
     * Sets <code>value</code> for variable moy2.
     * @param value value to bind as moy2
     */
    public void setmoy2(Number value) {
        ensureVariableManager().setVariableValue("moy2", value);
    }
    
}

