package model.readOnlyView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 09 12:04:25 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DiplomeEtudiantGradeROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DiplomeEtudiantGradeROVOImpl() {
    }
}

