package model.readOnlyView;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 19 09:53:33 UTC 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TextLoisByStructureRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdTextLoi {
            protected Object get(TextLoisByStructureRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(TextLoisByStructureRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdHistoriquesStructure {
            protected Object get(TextLoisByStructureRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(TextLoisByStructureRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Text {
            protected Object get(TextLoisByStructureRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(TextLoisByStructureRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Ordre {
            protected Object get(TextLoisByStructureRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(TextLoisByStructureRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        isSelected {
            protected Object get(TextLoisByStructureRowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(TextLoisByStructureRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(TextLoisByStructureRowImpl object);

        protected abstract void put(TextLoisByStructureRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDTEXTLOI = AttributesEnum.IdTextLoi.index();
    public static final int IDHISTORIQUESSTRUCTURE = AttributesEnum.IdHistoriquesStructure.index();
    public static final int TEXT = AttributesEnum.Text.index();
    public static final int ORDRE = AttributesEnum.Ordre.index();
    public static final int ISSELECTED = AttributesEnum.isSelected.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TextLoisByStructureRowImpl() {
    }
}

