package model.readOnlyView;

import java.math.BigInteger;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 18 11:04:28 GMT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NumDiplomeInsAncROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdNumeroDiplome {
            protected Object get(NumDiplomeInsAncROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NumDiplomeInsAncROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Numero {
            protected Object get(NumDiplomeInsAncROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NumDiplomeInsAncROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdHistoriqueStructure {
            protected Object get(NumDiplomeInsAncROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NumDiplomeInsAncROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LibelleLong {
            protected Object get(NumDiplomeInsAncROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NumDiplomeInsAncROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdAnneesUnivers {
            protected Object get(NumDiplomeInsAncROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NumDiplomeInsAncROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        HistoriquesStructuresROVO1 {
            protected Object get(NumDiplomeInsAncROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(NumDiplomeInsAncROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(NumDiplomeInsAncROVORowImpl object);

        protected abstract void put(NumDiplomeInsAncROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDNUMERODIPLOME = AttributesEnum.IdNumeroDiplome.index();
    public static final int NUMERO = AttributesEnum.Numero.index();
    public static final int IDHISTORIQUESTRUCTURE = AttributesEnum.IdHistoriqueStructure.index();
    public static final int LIBELLELONG = AttributesEnum.LibelleLong.index();
    public static final int IDANNEESUNIVERS = AttributesEnum.IdAnneesUnivers.index();
    public static final int HISTORIQUESSTRUCTURESROVO1 = AttributesEnum.HistoriquesStructuresROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NumDiplomeInsAncROVORowImpl() {
    }
}

